var allMusic = [

  {
      name: "Havana",
      artist: "Camila Cabello",
      src: "CamilaCabelloHavana",
      img: "CamilaCabelloHavana",
      style: "Energic",
      status: "nostatus",
      lyrics: {
        chorus: "Havana",
        verse1: "O na na na na na ",
        verse2: "O na na na na na ",
        verse3: "O na na na na na ",
        verse4: "O na na na na na ",
      }
  },
  {
      name: "Dj Is Your Second Name",
      artist: "C-Bool , Giang Pham",
      src: "C-BooLDJ",
      img: "C-BooLDJ",
      style: "Energic",
      status: "nostatus",
  },
  {
      name: "Never Go Away",
      artist: "C-Bool",
      src: "C-BooL-NeverGoAway",
      img: "C-BooL-NeverGoAway",
      style: "Energic",
      status: "nostatus",
  },
  {
      name: "Champions",
      artist: "Kevin Rudolf",
      src: "KevinRudolf-Champions",
      img: "KevinRudolf-Champions",
      style: "Energic",
      status: "nostatus",
  },
  {
      name: "Ride It",
      artist: "DJ Regard",
      src: "DJRegard-Rideit",
      img: "DJRegard-Rideit",
      style: "Energic",
      status: "nostatus",
  },
  {
      name: "Choker",
      artist: "Twenty one pilots",
      src: "twentyonepilots-Choker",
      img: "scaled-and-icy-b-iext104194001",
      style: "Energic",
      status: "nostatus",
  },
  {
      name: "The Outside",
      artist: "Twenty one pilots",
      src: "TwentyOnePilots-TheOutside",
      img: "scaled-and-icy-b-iext104194001",
      style: "Energic",
      status: "nostatus",
  },
  {
      name: "Shy Away",
      artist: "Twenty one pilots",
      src: "TwentyOnePilots-ShyAway",
      img: "scaled-and-icy-b-iext104194001",
      style: "Energic",
      status: "nostatus",
  },
  {
      name: "Saturday",
      artist: "Twenty one pilots",
      src: "TwentyOnePilots-Saturday",
      img: "scaled-and-icy-b-iext104194001",
      style: "Energic",
      status: "nostatus",
  },
  {
      name: "Redecorate",
      artist: "Twenty one pilots",
      src: "TwentyOnePilots-Redecorate",
      img: "scaled-and-icy-b-iext104194001",
      style: "Energic",
      status: "nostatus",
  },
  {
      name: "Never Take It",
      artist: "Twenty one pilots",
      src: "TwentyOnePilots-NeverTakeIt",
      img: "scaled-and-icy-b-iext104194001",
      style: "Energic",
      status: "nostatus",
  },
  {
      name: "Mulberry Street",
      artist: "Twenty one pilots",
      src: "TwentyOnePilots-MulberryStreet",
      img: "scaled-and-icy-b-iext104194001",
      style: "Energic",
      status: "nostatus",
  },
  {
      name: "Good Day",
      artist: "Twenty one pilots",
      src: "TwentyOnePilots-GoodDay",
      img: "scaled-and-icy-b-iext104194001",
      style: "Energic Hip-Hop",
      status: "nostatus",
  },
  {
      name: "Kłótnia",
      artist: "Evtis",
      src: "Evtis-Kłótnia",
      img: "C-BooL-NeverGoAway",
      style: "Hip-Hop",
      status: "nostatus",
  },
  {
      name: "Idziemy Po Swoje",
      artist: "Szusty , Guralsko",
      src: "donGURALesko-IdziemyPoSwojeSzUstyBlend",
      img: "guralsko",
      style: "Hip-Hop",
      status: "nostatus",
  },
  {
      name: "Legenda",
      artist: "Szusty , Guralsko",
      src: "donGURALesko-LegendaSzUstyBlend",
      img: "guralsko",
      style: "Hip-Hop",
      status: "nostatus",
  },
]
