var allMusic = [

  {
      name: "Havana",
      artist: "Camila Cabello",
      src: "CamilaCabelloHavana",
      img: "CamilaCabelloHavana",
      style: "Energic",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f45bsf",
      id: "0",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
  },
  {
      name: "Dj Is Your Second Name",
      artist: "C-Bool",
      src: "C-BooLDJ",
      img: "C-BooLDJ",
      style: "Energic",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f25bsf",
      id: "1",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
  },
  {
      name: "Never Go Away",
      artist: "C-Bool",
      src: "C-BooL-NeverGoAway",
      img: "C-BooL-NeverGoAway",
      style: "Energic",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f25bsf",
      id: "2",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
  },
  {
      name: "Champions",
      artist: "Kevin Rudolf",
      src: "KevinRudolf-Champions",
      img: "KevinRudolf-Champions",
      style: "Workout",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f31bsf",
      id: "3",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
  },
  {
      name: "Ride It",
      artist: "DJ Regard",
      src: "DJRegard-Rideit",
      img: "DJRegard-Rideit",
      style: "Energic",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f21bsf",
      id: "4",
      lyrics:{
        lyrics_verse_1: "Just lose control Ride it, ride it, come touch my soul Ride it, ride it, let me feel you Ride it, turn the lights down low Ride it, from head to toe Ride it, ride it, come touch my soul Ride it, ride it, let me feel you",
        lyrics_verse_2: "It's been a month and twenty days And we're going 'round and 'round, playing silly games Now you're saying, slow it down, not right now Then you wink at me and walk away Let it be, let it be, let it be known Hold on, don't go Touching and teasing me, telling me no But this time I need to feel you",
        lyrics_verse_3: "Ride it, we're all alone Ride it, just lose control Ride it, ride it, come touch my soul Ride it, ride it, let me feel you Ride it, turn the lights down low Ride it, from head to toe Ride it, ride it, come touch my soul Ride it, ride it, let me feel you",
        lyrics_verse_4: "Movida was the club on the Saturday You're actin' like a diva, sayin' you don't wanna pay It's gotta be ya feisty style, raised eyebrow I love it when you look at me that way Now we're in, you order a mojito at the bar Re-apply your lippy 'cause it came off on the glass The DJ plays your favorite song, Kanye's on Now ya beckoning for me to dance Mm, pullin' me, pullin' me, pullin' me close Just close your eyes, girl Whispering, tellin' me, we gotta go Won't you take me home? I wanna",
        lyrics_verse_5: "Ride it, we're all alone Ride it, just lose control Ride it, ride it, come touch my soul Ride it, ride it, let me feel you Ride it, turn the lights down low Ride it, from head to toe Ride it, ride it, come touch my soul Ride it, ride it, let me feel you",
        lyrics_verse_6: "Ride it, we're all alone Ride it, just lose control Ride it, ride it, come touch my soul Ride it, ride it, let me feel you Ride it, turn the lights down low Ride it, from head to toe Ride it, ride it, come touch my soul Ride it, ride it, let me feel you",
        lyrics_verse_7: "Won't you take me home? I wanna, Ride it, we're all alone Ride it, just lose control Ride it, ride it, come touch my soul Ride it, ride it, let me feel you Ride it, turn the lights down low Ride it, from head to toe Ride it, ride it, come touch my soul Ride it, ride it, let me feel you",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
  },
  {
      name: "Choker",
      artist: "Twenty one pilots",
      src: "twentyonepilots-Choker",
      img: "scaled-and-icy-b-iext104194001",
      style: "Chill",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f22bsf",
      id: "5",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
  },
  {
      name: "The Outside",
      artist: "Twenty one pilots",
      src: "TwentyOnePilots-TheOutside",
      img: "scaled-and-icy-b-iext104194001",
      style: "Chill",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f22bsf",
      id: "6",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
  },
  {
      name: "Shy Away",
      artist: "Twenty one pilots",
      src: "TwentyOnePilots-ShyAway",
      img: "scaled-and-icy-b-iext104194001",
      style: "Chill",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f22bsf",
      id: "7",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
  },
  {
      name: "Saturday",
      artist: "Twenty one pilots",
      src: "TwentyOnePilots-Saturday",
      img: "scaled-and-icy-b-iext104194001",
      style: "Chill",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f22bsf",
      id: "8",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
  },
  {
      name: "Redecorate",
      artist: "Twenty one pilots",
      src: "TwentyOnePilots-Redecorate",
      img: "scaled-and-icy-b-iext104194001",
      style: "Chill",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f22bsf",
      id: "9",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
  },
  {
      name: "Never Take It",
      artist: "Twenty one pilots",
      src: "TwentyOnePilots-NeverTakeIt",
      img: "scaled-and-icy-b-iext104194001",
      style: "Chill",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f22bsf",
      id: "10",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
  },
  {
      name: "Mulberry Street",
      artist: "Twenty one pilots",
      src: "TwentyOnePilots-MulberryStreet",
      img: "scaled-and-icy-b-iext104194001",
      style: "Chill",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f22bsf",
      id: "11",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
  },
  {
      name: "Good Day",
      artist: "Twenty one pilots",
      src: "TwentyOnePilots-GoodDay",
      img: "scaled-and-icy-b-iext104194001",
      style: "Chill",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f22bsf",
      id: "12",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
  },
  {
      name: "Kłótnia",
      artist: "Evtis",
      src: "Evtis-Kłótnia",
      img: "C-BooL-NeverGoAway",
      style: "Hip-Hop",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f106bsf",
      id: "13",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
  },
  {
      name: "Idziemy Po Swoje",
      artist: "Szusty , Guralsko",
      src: "donGURALesko-IdziemyPoSwojeSzUstyBlend",
      img: "guralsko",
      style: "Workout",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f46bsf",
      id: "14",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
  },
  {
      name: "Legenda",
      artist: "Szusty , Guralsko",
      src: "donGURALesko-LegendaSzUstyBlend",
      img: "guralsko",
      style: "Workout",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f46bsf",
      id: "15",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
      
  },
  {
    name: "Rockstar",
    artist: "Post Malone",
    src: "PostMalone-Rockstar",
    img: "rockstar-w-iext111232885",
    style: "Pop",
    status: "nostatus",
    avatar: "41aeb62f0=c2321-f23bsf",
    id: "16",
    lyrics:{
      lyrics_verse_1: "",
      lyrics_verse_2: "",
      lyrics_verse_3: "",
      lyrics_verse_4: "",
      lyrics_verse_5: "",
      lyrics_verse_6: "",
      lyrics_verse_7: "",
      lyrics_verse_8: "",
      lyrics_verse_9: "",
      lyrics_verse_10: "",
      lyrics_verse_11: "",
      lyrics_verse_12: "",
      lyrics_verse_13: "",
      lyrics_verse_14: ""
    },
  },
  {
    name: "Bez Znieczulenia",
    artist: "Happysad",
    src: "Happysad-Bezznieczulenia",
    img: "ab67616d00001e021f86dffe512418a230887e69",
    style: "Rock",
    status: "nostatus",
    avatar: "14235843737BeNz9sRRfK4jsYeLQ7t32Pg76m86w",
    id: "17",
    lyrics:{
      lyrics_verse_1: "",
      lyrics_verse_2: "",
      lyrics_verse_3: "",
      lyrics_verse_4: "",
      lyrics_verse_5: "",
      lyrics_verse_6: "",
      lyrics_verse_7: "",
      lyrics_verse_8: "",
      lyrics_verse_9: "",
      lyrics_verse_10: "",
      lyrics_verse_11: "",
      lyrics_verse_12: "",
      lyrics_verse_13: "",
      lyrics_verse_14: ""
    },
  },
  {
    name: "Pętla",
    artist: "Happysad",
    src: "Happysad-Pętla",
    img: "ab67616d00001e021f86dffe512418a230887e69",
    style: "Rock",
    status: "nostatus",
    avatar: "14235843737BeNz9sRRfK4jsYeLQ7t32Pg76m86w",
    id: "18",
    lyrics:{
      lyrics_verse_1: "",
      lyrics_verse_2: "",
      lyrics_verse_3: "",
      lyrics_verse_4: "",
      lyrics_verse_5: "",
      lyrics_verse_6: "",
      lyrics_verse_7: "",
      lyrics_verse_8: "",
      lyrics_verse_9: "",
      lyrics_verse_10: "",
      lyrics_verse_11: "",
      lyrics_verse_12: "",
      lyrics_verse_13: "",
      lyrics_verse_14: ""
    },
  },
  {
    name: "Tired Bones",
    artist: "L.B.ONE",
    src: "LBONE-TiredBones",
    img: "tired-bones-w-iext52557958",
    style: "Energic",
    status: "nostatus",
    avatar: "5cd42c454b86e992d288a65bd8a187b62151",
    id: "19",
    lyrics:{
      lyrics_verse_1: "",
      lyrics_verse_2: "",
      lyrics_verse_3: "",
      lyrics_verse_4: "",
      lyrics_verse_5: "",
      lyrics_verse_6: "",
      lyrics_verse_7: "",
      lyrics_verse_8: "",
      lyrics_verse_9: "",
      lyrics_verse_10: "",
      lyrics_verse_11: "",
      lyrics_verse_12: "",
      lyrics_verse_13: "",
      lyrics_verse_14: ""
    },
  },
  {
    name: "Złap Za Broń",
    artist: "Trzeci Wymiar",
    src: "TrzeciWymiar-Złapzabroń",
    img: "6341ef2bd3abc2c21c6ee6466cb67d15.510x510x1",
    style: "Hip-Hop",
    status: "nostatus",
    avatar: "41aeb62f0-c2321-f24bsf",
    id: "20",
    lyrics:{
      lyrics_verse_1: "",
      lyrics_verse_2: "",
      lyrics_verse_3: "",
      lyrics_verse_4: "",
      lyrics_verse_5: "",
      lyrics_verse_6: "",
      lyrics_verse_7: "",
      lyrics_verse_8: "",
      lyrics_verse_9: "",
      lyrics_verse_10: "",
      lyrics_verse_11: "",
      lyrics_verse_12: "",
      lyrics_verse_13: "",
      lyrics_verse_14: ""
    },
  },
  {
    name: "I'm Not Rich",
    artist: "The King's Son",
    src: "TheKingsSon-ImNotRich",
    img: "ab67616d0000b27369cdca7b90ca8060e3525196",
    style: "Chill",
    status: "nostatus",
    avatar: "41aeb62f0=c2321-f56bsf",
    id: "21",
    lyrics:{
      lyrics_verse_1: "",
      lyrics_verse_2: "",
      lyrics_verse_3: "",
      lyrics_verse_4: "",
      lyrics_verse_5: "",
      lyrics_verse_6: "",
      lyrics_verse_7: "",
      lyrics_verse_8: "",
      lyrics_verse_9: "",
      lyrics_verse_10: "",
      lyrics_verse_11: "",
      lyrics_verse_12: "",
      lyrics_verse_13: "",
      lyrics_verse_14: ""
    },
  },
  {
    name: "Invincible",
    artist: "MGK",
    src: "MGK-Invincible",
    img: "ab67616d0000b273a57d3a2736f815d3cf358e37",
    style: "Workout",
    status: "nostatus",
    avatar: "41aeb62f0=c2321-f57bsf",
    id: "22",
    lyrics:{
      lyrics_verse_1: "",
      lyrics_verse_2: "",
      lyrics_verse_3: "",
      lyrics_verse_4: "",
      lyrics_verse_5: "",
      lyrics_verse_6: "",
      lyrics_verse_7: "",
      lyrics_verse_8: "",
      lyrics_verse_9: "",
      lyrics_verse_10: "",
      lyrics_verse_11: "",
      lyrics_verse_12: "",
      lyrics_verse_13: "",
      lyrics_verse_14: ""
    },
  },
  {
    name: "In The Name Of Love",
    artist: "Bebe Rexha",
    src: "BebeRexha-InTheNameOfLove",
    img: "ab67616d0000b2738c77bcf5f5a227d270d23370",
    style: "Energic",
    status: "nostatus",
    avatar: "41aeb62f0=c2321-f58bsf",
    id: "23",
    lyrics:{
      lyrics_verse_1: "",
      lyrics_verse_2: "",
      lyrics_verse_3: "",
      lyrics_verse_4: "",
      lyrics_verse_5: "",
      lyrics_verse_6: "",
      lyrics_verse_7: "",
      lyrics_verse_8: "",
      lyrics_verse_9: "",
      lyrics_verse_10: "",
      lyrics_verse_11: "",
      lyrics_verse_12: "",
      lyrics_verse_13: "",
      lyrics_verse_14: ""
    },
  },
]
