var movies = [
    {
        name: "Władca Pierścieni: Drużyna Pierścienia",
        director: "Peter Jackson",
        art: "https://fwcdn.pl/fpo/10/65/1065/7912491.6.jpg",
        pageLink: "lord-of-the-rings-the-fellowship-of-the-ring.html",
        date: "2001",
        tag: "ACTION",
    },
    {
        name: "Władca Pierścieni: Dwie wieże",
        director: "Peter Jackson",
        art: "https://filman.cc/public/static/poster/big/51423.jpg",
        pageLink: "lord-of-the-rings-the-two-towers.html",
        date: "2002",
        tag: "ACTION",
    },
    {
        name: "Władca Pierścieni: Powrót Króla",
        director: "Peter Jackson",
        art: "https://fwcdn.pl/fpo/18/41/11841/7494142.6.jpg",
        pageLink: "lord-of-the-rings-the-return-of-the-king.html",
        date: "2003",
        tag: "ACTION",
    },
    {
        name: "Gladiator",
        director: "Ridley Scott",
        art: "https://filman.cc/public/static/poster/big/48810.jpg",
        pageLink: "gladiator.html",
        date: "1999",
        tag: "ACTION",
    },
    {
        name: "Hobbit: Niezwykła Podróż",
        director: "Peter Jackson",
        art: "https://filman.cc/public/static/poster/big/219.jpg",
        pageLink: "hobbit-niezwykla-podroz.html",
        date: "2012",
        tag: "ACTION",
    },
    {
        name: "Hobbit: Pustkowie Smauga",
        director: "Peter Jackson",
        art: "https://fwcdn.pl/fpo/98/67/469867/7585361.6.jpg",
        pageLink: "hobbit-pustkowie-smauga.html",
        date: "2013",
        tag: "ACTION",
    },
    {
        name: "Hobbit: Bitwa Pięciu Armii",
        director: "Peter Jackson",
        art: "https://fwcdn.pl/fpo/22/42/662242/7628118.6.jpg",
        pageLink: "hobbit-bitwa-pieciu-armii.html",
        date: "2014",
        tag: "ACTION",
    },
    {
        name: "Furia",
        director: "David Ayer",
        art: "https://filman.cc/public/static/poster/big/39587.jpg",
        pageLink: "furia-fury.html",
        date: "2014",
        tag: "ACTION",
    },
    {
        name: "1917",
        director: "Sam Mendes",
        art: "https://filman.cc/public/static/poster/big/30135.jpg",
        pageLink: "1917.html",
        date: "2019",
        tag: "ACTION",
    },
    {
        name: "Opowieści z Narnii: Lew, Czarownica i stara szafa",
        director: "Andrew Adamson",
        art: "https://filman.cc/public/static/poster/big/38333.jpg",
        pageLink: "opowiesci-z-narnii-lew-czarownica-i-stara-szafa.html",
        date: "2005",
        tag: "ADVENTURE",
    },
]