var movies = [
    {
        name: "Władca Pierścieni: Drużyna Pierścienia",
        director: "Peter Jackson",
        link: "https://str10.vidoza.net/nvl4gmvu4ieuieno3xfqhah7pdavvi36k7iccptx7gheopnwvmkqhzindrda/v.mp4",
        art: "https://fwcdn.pl/fpo/10/65/1065/7912491.6.jpg",
        header: "https://wallpapercave.com/wp/wp7486055.jpg",
        description: "Kiedyś, na pamiętnej wyprawie pod Samotną Górę Bilbo Baggins (Ian Holm) zdobył przez przypadek pierścień. Jeden z jego starych dobrych znajomych, który także uczestniczył w tamtej wyprawie - czarodziej Gandalf (Ian McKellen), zaczyna teraz podejrzewać, że jest to Jedyny Pierścień, który może dać władzę nad światem. Został on dawno temu stworzony przez Saurona we wnętrzu Góry Zagłady i teraz jego twórca chce go odzyskać, by zrealizować swoje niebezpieczne plany. Frodo Baggins (Elijah Wood), który otrzymał ten pierścień od Bilba, musi uciekać. Na naradzie w Rivendell zostaje podjęta decyzja, że drużyna złożona z dziewięciu przedstawicieli różnych ras podejmie się razem z Frodem - Powiernikiem Pierścienia - wykonać misję zniszczenia potężnego pierścienia. W Śródziemiu zanosi się na wojnę. Robi się niebezpiecznie, pojawiają się tajemniczy Czarni Jeźdźcy. Losy tej wojny nie będą jednak zależeć tak naprawdę od rozkładu sił militarnych. Wszystkie wojska będą jedynie przykrywką, losy świata zależą od Drużyny Pierścienia i od tego, czy Powiernik Pierścienia ukończy szczęśliwie swoją misję. Jest to o tyle trudniejsze, że Pierścień Władzy budzi silne pożądanie w ludziach, którzy się z nim stykają i potrafi zawładnąć ich psychiką, jeśli nie będą wystarczająco odporni. W ślad za Drużyną rusza między innymi jedna z ofiar Pierścienia Władzy - Gollum (Andy Serkis), który posunie się do wszystkiego, by odzyskać Pierścień, który kiedyś zrujnował jego życie i zrobił z niego potwora.",
        trailer: "https://www.youtube.com/watch?v=V75dMMIW2B4&ab_channel=Movieclips",
        category_1: "ACTION",
        category_2: "FANTASY",
        category_3: "SCI-FI",
        category_4: "POPULAR",
        preview: "",
        pageLink: "lord-of-the-rings-the-fellowship-of-the-ring.html",
        rate: "9.2",
        date: "2001",
        gallery1: "https://static1.srcdn.com/wordpress/wp-content/uploads/2020/06/Viggo-Mortensen-as-Aragorn-in-Lord-of-the-Rings.jpg",
        gallery2: "https://bbts1.azureedge.net/images/p/full/2021/01/049b507b-4372-49c8-adc8-5ecd63176cc8.jpg",
        gallery3: "https://www.slantmagazine.com/wp-content/uploads/2018/05/returnoftheking.jpg",
        gallery4: "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2021/04/Untitled-design-4.jpg",
    },
    {
        name: "Władca Pierścieni: Dwie wieże",
        director: "Peter Jackson",
        link: "https://str10.vidoza.net/nvl4gmvu4ieuieno3xfqhah7pdavvi36k7iccptx7gheopnwvmkqhzindrda/v.mp4",
        art: "https://filman.cc/public/static/poster/big/51423.jpg",
        header: "https://wallpapercave.com/wp/wp7486055.jpg",
        description: "Kontynuacja filmowej adaptacji Władcy Pierścieni. Po śmierci Boromira (Sean Bean) Aragorn (Viggo Mortensen), Gimli (John Rhys-Davies) i Legolas (Orlando Bloom) wyruszają tropem porwanych hobbitów, Merry'ego (Dominic Monaghan) i Pippina (Billy Boyd). Tymczasem Frodo (Elijah Wood) i Sam (Sean Astin) obierają drogę do Mordoru. Ich tropem podąża dawny posiadacz pierścienia, Gollum (Andy Serkis). Frodo i Sam obserwują wymarsz wojsk z wrogiej twierdzy Minas Morgul. Wojna jest nieunikniona. Wojna trzech armii, gdyż zdrajca Saruman (Christopher Lee) również przygotowuje swoją armię Uruk-Hai do napaści na niczego niespodziewające się królestwo Władców Koni, Rohanu.",
        trailer: "https://www.youtube.com/watch?v=LbfMDwc4azU&ab_channel=RottenTomatoesClassicTrailers",
        category_1: "ACTION",
        category_2: "FANTASY",
        category_3: "SCI-FI",
        category_4: "POPULAR",
        preview: "",
        pageLink: "lord-of-the-rings-the-two-towers.html",
        rate: "9.3",
        date: "2002",
        gallery1: "https://static1.srcdn.com/wordpress/wp-content/uploads/2020/06/Viggo-Mortensen-as-Aragorn-in-Lord-of-the-Rings.jpg",
        gallery2: "https://bbts1.azureedge.net/images/p/full/2021/01/049b507b-4372-49c8-adc8-5ecd63176cc8.jpg",
        gallery3: "https://www.slantmagazine.com/wp-content/uploads/2018/05/returnoftheking.jpg",
        gallery4: "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2021/04/Untitled-design-4.jpg",
    },
]