var allMusic = [

  {
      name: "Havana",
      artist: "Camila Cabello",
      src: "CamilaCabelloHavana",
      img: "CamilaCabelloHavana",
      style: "Energic",
      status: "nostatus",
      tag: "Popular",
      avatar: "41aeb62f0-c2321-f45bsf",
      artist_img: "https://i.scdn.co/image/ab6761610000e5ebec05963eab63676a539fef13",
      album: "Camila",
      album_cover: "https://i.scdn.co/image/ab67616d00001e026eb0b9e73adcf04e4ed3eca4",
      album_premiere: "2018",
      id: "0",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
      bio: "Multi-Grammy nominated Cuban born singer/songwriter Camila Cabello released her debut solo album, CAMILA in January 2018 to rave reviews. It debuted at #1 on the Billboard 200 chart at the same time as her single “Havana” reached #1 on the Billboard Hot 100 chart, making her the first solo artist in nearly 15 years to reach the #1 spot on the Hot 100, Billboard 200 & Artist 100 charts in the same week. CAMILA launched its debut at #1 on 110 iTunes charts around the world, breaking the record for most #1 positions for a debut album in iTunes history. Camila also became the #1 artist on global Spotify. She released her RIAA 9x platinum smash hit “Havana,” in August 2017 where it obtained the #1 spot on the pop radio chart. “Havana” is the first song by a female artist to reach No. 1 on Billboard’s Adult Contemporary, Pop Songs & Rhythmic Songs charts in 22 years, has earned over 1.1 billion on-demand U.S. streams, according to Nielsen Music, & attained the longest run at No. 1 on Pop Songs for any song by a female artist since 2013. Havana became the most streamed song of all time by a female artist & was the number one song of 2018 globally. Her triple-platinum single “Never Be The Same,” was released in January 2018 & peaked in the top 10 of the Billboard Hot 100 chart. Camila became the first artist in history to have two multi-format number one singles as the first two singles from their debut album. In November 2018, she was named the new ambassador for Save the Children.",
      social:{
        instagram: "https://www.instagram.com/camila_cabello/",
        twitter: "https://twitter.com/camila_cabello",
        facebook: "https://www.facebook.com/camilacabello",
      },
      user_playlist_1: "",
  },
  {
      name: "Dj Is Your Second Name",
      artist: "C-Bool",
      src: "C-BooLDJ",
      img: "C-BooLDJ",
      style: "Energic",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f25bsf",
      artist_img: "https://i.scdn.co/image/ab6761610000e5eb00a89c0f54687319c9a499de",
      album: "Dj Is Your Second Name",
      album_cover: "https://i.scdn.co/image/ab67616d0000b2734470a94060697a4265fb0e03",
      album_premiere: "2017",
      id: "1",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
      bio: "C-BooL (Grzegorz Cebula) was born on May 30, 1981 in Pyskowice in Silesia (Poland). Polish DJ, music producer and owner of C-Wave Records. Associated with club music from an early age. Works as a DJ since 1998 and started producing music in 2002. Diamond, multi platinum and golden records producer of many radio hits like Never Go Away, DJ Is Your Second Name, Magic Symphony, Wonderland, Catch You, Fire In My Head, La La Love and older club classics like Would You Feel and House Baby. Two-time winner of the Eska Music Awards in the hit of the year category (2016 & 2017). No 1 Hits - Shazam Poland, Radio Airplay Poland Top 3 Hits Airplay Russia In his 23-year DJ career C-BooL performed in hundreds of clubs in Poland and abroad. His DJ sets were presented in countries such as Germany, Austria, Italy, Bulgaria & UK",
      social:{
        instagram: "",
        twitter: "",
        facebook: "https://www.facebook.com/cboolmusic",
      },
      user_playlist_1: "",
  },
  {
      name: "Never Go Away",
      artist: "C-Bool",
      src: "C-BooL-NeverGoAway",
      img: "C-BooL-NeverGoAway",
      style: "Energic",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f25bsf",
      artist_img: "https://i.scdn.co/image/ab6761610000e5eb00a89c0f54687319c9a499de",
      album: "Never Go Away",
      album_cover: "https://i.scdn.co/image/ab67616d00001e0225a6f8a62f4d061ef61169c9",
      album_premiere: "2016",
      id: "2",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
      bio: "C-BooL (Grzegorz Cebula) was born on May 30, 1981 in Pyskowice in Silesia (Poland). Polish DJ, music producer and owner of C-Wave Records. Associated with club music from an early age. Works as a DJ since 1998 and started producing music in 2002. Diamond, multi platinum and golden records producer of many radio hits like Never Go Away, DJ Is Your Second Name, Magic Symphony, Wonderland, Catch You, Fire In My Head, La La Love and older club classics like Would You Feel and House Baby. Two-time winner of the Eska Music Awards in the hit of the year category (2016 & 2017). No 1 Hits - Shazam Poland, Radio Airplay Poland Top 3 Hits Airplay Russia In his 23-year DJ career C-BooL performed in hundreds of clubs in Poland and abroad. His DJ sets were presented in countries such as Germany, Austria, Italy, Bulgaria & UK",
      social:{
        instagram: "",
        twitter: "",
        facebook: "https://www.facebook.com/cboolmusic",
      },
      user_playlist_1: "",
  },
  {
      name: "Champions",
      artist: "Kevin Rudolf",
      src: "KevinRudolf-Champions",
      img: "KevinRudolf-Champions",
      style: "Workout",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f31bsf",
      artist_img: "https://i.scdn.co/image/ab6761610000e5ebf977eaad9f10f82d6b3e3278",
      album: "Champions",
      album_cover: "https://i.scdn.co/image/ab67616d00001e02335815746144562adb8455b4",
      album_premiere: "2012",
      id: "3",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
      bio: "A rocker running in rap circles, singer/songwriter/producer Kevin Rudolf worked on multiple hit songs before making his own bid for stardom as the first rock artist signed to rap label",
      social:{
        instagram: "https://www.instagram.com/kevinrudolf/?theme=dark",
        twitter: "https://twitter.com/kevinrudolf",
        facebook: "https://www.facebook.com/kevinrudolf/?eid=ARDXHcejUXCfQ99mrwayQUj_NWr41eTSTGWFhdYz-QCptcsP-JGRWgapKE7Cgfs8GlZ6wa9UK7Cud_oO",
      },
      user_playlist_1: "",
  },
  {
      name: "Ride It",
      artist: "DJ Regard",
      src: "DJRegard-Rideit",
      img: "DJRegard-Rideit",
      style: "Energic",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f21bsf",
      artist_img: "https://i.scdn.co/image/ab6761610000e5ebf2463642042d6e99c687b42c",
      album: "Ride It",
      album_cover: "https://i.scdn.co/image/ab67616d00001e025c27813ae019011fcb370c78",
      album_premiere: "2019",
      id: "4",
      lyrics:{
        lyrics_verse_1: "Just lose control Ride it, ride it, come touch my soul Ride it, ride it, let me feel you Ride it, turn the lights down low Ride it, from head to toe Ride it, ride it, come touch my soul Ride it, ride it, let me feel you",
        lyrics_verse_2: "It's been a month and twenty days And we're going 'round and 'round, playing silly games Now you're saying, slow it down, not right now Then you wink at me and walk away Let it be, let it be, let it be known Hold on, don't go Touching and teasing me, telling me no But this time I need to feel you",
        lyrics_verse_3: "Ride it, we're all alone Ride it, just lose control Ride it, ride it, come touch my soul Ride it, ride it, let me feel you Ride it, turn the lights down low Ride it, from head to toe Ride it, ride it, come touch my soul Ride it, ride it, let me feel you",
        lyrics_verse_4: "Movida was the club on the Saturday You're actin' like a diva, sayin' you don't wanna pay It's gotta be ya feisty style, raised eyebrow I love it when you look at me that way Now we're in, you order a mojito at the bar Re-apply your lippy 'cause it came off on the glass The DJ plays your favorite song, Kanye's on Now ya beckoning for me to dance Mm, pullin' me, pullin' me, pullin' me close Just close your eyes, girl Whispering, tellin' me, we gotta go Won't you take me home? I wanna",
        lyrics_verse_5: "Ride it, we're all alone Ride it, just lose control Ride it, ride it, come touch my soul Ride it, ride it, let me feel you Ride it, turn the lights down low Ride it, from head to toe Ride it, ride it, come touch my soul Ride it, ride it, let me feel you",
        lyrics_verse_6: "Ride it, we're all alone Ride it, just lose control Ride it, ride it, come touch my soul Ride it, ride it, let me feel you Ride it, turn the lights down low Ride it, from head to toe Ride it, ride it, come touch my soul Ride it, ride it, let me feel you",
        lyrics_verse_7: "Won't you take me home? I wanna, Ride it, we're all alone Ride it, just lose control Ride it, ride it, come touch my soul Ride it, ride it, let me feel you Ride it, turn the lights down low Ride it, from head to toe Ride it, ride it, come touch my soul Ride it, ride it, let me feel you",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
      bio: "Kosovan DJ & Producer Regard built up over 1 million Subscribers through his series of deep house mixes, remixes and original tracks in support of LEAF Management signed since of 2012. In July 2019 Regard released his first official single 'Ride It' in the other label at Ministry of Sound and managed by LEAF Management. 'Ride It' became an international hit, taking the internet and TikTok by storm, achieving over ten top 10 single chart placements globally, including #2 in the UK where 'Ride It' is now Certified Multi-Platinum. Regard finished the 'Ride It' campaign with an amazing debut at Capital's Jingle Bell Ball, and on his first TV performance in UK at Top of The Pops. Regard remixing Dua Lipa's hit 'Don't Start Me Now at February. Regard has released the latest record 'Secrets' featuring with Raye by the end of April, while it's running very well as second record by Regard. Regard contacts: ",
      social:{
        instagram: "https://www.instagram.com/djregardofficial/?theme=dark",
        twitter: "https://twitter.com/DardanRegard",
        facebook: "https://www.facebook.com/DjRegardOfficial/",
      },
      user_playlist_1: "",
  },
  {
      name: "Choker",
      artist: "Twenty one pilots",
      src: "twentyonepilots-Choker",
      img: "scaled-and-icy-b-iext104194001",
      style: "Chill",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f22bsf",
      artist_img: "https://i.scdn.co/image/ab6761610000e5eb196972172c37d934d9ca8093",
      album: "Scaled And Icy",
      album_cover: "https://i.scdn.co/image/ab67616d00001e0220b467550945fd123e00f0a5",
      album_premiere: "2021",
      id: "5",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
      bio: "Twenty One Pilots shook the world with the release of their 2015 LP BLURRYFACE, an album that would go on to sell over 7 million copies worldwide and earn the band their first ever GRAMMY® Award as they shattered longstanding chart records, and captivated audiences worldwide on sold-out arena runs and at international festivals.  Now three years later, the duo of Tyler Joseph and Josh Dun have returned to write the next chapter of their story with TRENCH, the band’s highly anticipated new studio album.  TRENCH finds Twenty One Pilots fearlessly reimagining the possibilities of their music through the same candid expression and genuine identity that helped to cement their place as one of the largest bands in the world.",
      social:{
        instagram: "https://www.instagram.com/twentyonepilots/?theme=dark",
        twitter: "https://twitter.com/twentyonepilots",
        facebook: "https://www.facebook.com/twentyonepilots",
      },
      user_playlist_1: "",
  },
  {
      name: "The Outside",
      artist: "Twenty one pilots",
      src: "TwentyOnePilots-TheOutside",
      img: "scaled-and-icy-b-iext104194001",
      style: "Chill",
      status: "nostatus",
      tag: "Popular",
      avatar: "41aeb62f0-c2321-f22bsf",
      artist_img: "https://i.scdn.co/image/ab6761610000e5eb196972172c37d934d9ca8093",
      album: "Scaled And Icy",
      album_cover: "https://i.scdn.co/image/ab67616d00001e0220b467550945fd123e00f0a5",
      album_premiere: "2021",
      id: "6",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
      bio: "Twenty One Pilots shook the world with the release of their 2015 LP BLURRYFACE, an album that would go on to sell over 7 million copies worldwide and earn the band their first ever GRAMMY® Award as they shattered longstanding chart records, and captivated audiences worldwide on sold-out arena runs and at international festivals.  Now three years later, the duo of Tyler Joseph and Josh Dun have returned to write the next chapter of their story with TRENCH, the band’s highly anticipated new studio album.  TRENCH finds Twenty One Pilots fearlessly reimagining the possibilities of their music through the same candid expression and genuine identity that helped to cement their place as one of the largest bands in the world.",
      social:{
        instagram: "https://www.instagram.com/twentyonepilots/?theme=dark",
        twitter: "https://twitter.com/twentyonepilots",
        facebook: "https://www.facebook.com/twentyonepilots",
      },
      user_playlist_1: "",
  },
  {
      name: "Shy Away",
      artist: "Twenty one pilots",
      src: "TwentyOnePilots-ShyAway",
      img: "scaled-and-icy-b-iext104194001",
      style: "Chill",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f22bsf",
      artist_img: "https://i.scdn.co/image/ab6761610000e5eb196972172c37d934d9ca8093",
      album: "Scaled And Icy",
      album_cover: "https://i.scdn.co/image/ab67616d00001e0220b467550945fd123e00f0a5",
      album_premiere: "2021",
      id: "7",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
      bio: "Twenty One Pilots shook the world with the release of their 2015 LP BLURRYFACE, an album that would go on to sell over 7 million copies worldwide and earn the band their first ever GRAMMY® Award as they shattered longstanding chart records, and captivated audiences worldwide on sold-out arena runs and at international festivals.  Now three years later, the duo of Tyler Joseph and Josh Dun have returned to write the next chapter of their story with TRENCH, the band’s highly anticipated new studio album.  TRENCH finds Twenty One Pilots fearlessly reimagining the possibilities of their music through the same candid expression and genuine identity that helped to cement their place as one of the largest bands in the world.",
      social:{
        instagram: "https://www.instagram.com/twentyonepilots/?theme=dark",
        twitter: "https://twitter.com/twentyonepilots",
        facebook: "https://www.facebook.com/twentyonepilots",
      },
      user_playlist_1: "",
  },
  {
      name: "Saturday",
      artist: "Twenty one pilots",
      src: "TwentyOnePilots-Saturday",
      img: "scaled-and-icy-b-iext104194001",
      style: "Chill",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f22bsf",
      artist_img: "https://i.scdn.co/image/ab6761610000e5eb196972172c37d934d9ca8093",
      album: "Scaled And Icy",
      album_cover: "https://i.scdn.co/image/ab67616d00001e0220b467550945fd123e00f0a5",
      album_premiere: "2021",
      id: "8",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
      bio: "Twenty One Pilots shook the world with the release of their 2015 LP BLURRYFACE, an album that would go on to sell over 7 million copies worldwide and earn the band their first ever GRAMMY® Award as they shattered longstanding chart records, and captivated audiences worldwide on sold-out arena runs and at international festivals.  Now three years later, the duo of Tyler Joseph and Josh Dun have returned to write the next chapter of their story with TRENCH, the band’s highly anticipated new studio album.  TRENCH finds Twenty One Pilots fearlessly reimagining the possibilities of their music through the same candid expression and genuine identity that helped to cement their place as one of the largest bands in the world.",
      social:{
        instagram: "https://www.instagram.com/twentyonepilots/?theme=dark",
        twitter: "https://twitter.com/twentyonepilots",
        facebook: "https://www.facebook.com/twentyonepilots",
      },
      user_playlist_1: "",
  },
  {
      name: "Redecorate",
      artist: "Twenty one pilots",
      src: "TwentyOnePilots-Redecorate",
      img: "scaled-and-icy-b-iext104194001",
      style: "Chill",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f22bsf",
      artist_img: "https://i.scdn.co/image/ab6761610000e5eb196972172c37d934d9ca8093",
      album: "Scaled And Icy",
      album_cover: "https://i.scdn.co/image/ab67616d00001e0220b467550945fd123e00f0a5",
      album_premiere: "2021",
      id: "9",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
      bio: "Twenty One Pilots shook the world with the release of their 2015 LP BLURRYFACE, an album that would go on to sell over 7 million copies worldwide and earn the band their first ever GRAMMY® Award as they shattered longstanding chart records, and captivated audiences worldwide on sold-out arena runs and at international festivals.  Now three years later, the duo of Tyler Joseph and Josh Dun have returned to write the next chapter of their story with TRENCH, the band’s highly anticipated new studio album.  TRENCH finds Twenty One Pilots fearlessly reimagining the possibilities of their music through the same candid expression and genuine identity that helped to cement their place as one of the largest bands in the world.",
      social:{
        instagram: "https://www.instagram.com/twentyonepilots/?theme=dark",
        twitter: "https://twitter.com/twentyonepilots",
        facebook: "https://www.facebook.com/twentyonepilots",
      },
      user_playlist_1: "",
  },
  {
      name: "Never Take It",
      artist: "Twenty one pilots",
      src: "TwentyOnePilots-NeverTakeIt",
      img: "scaled-and-icy-b-iext104194001",
      style: "Chill",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f22bsf",
      artist_img: "https://i.scdn.co/image/ab6761610000e5eb196972172c37d934d9ca8093",
      album: "Scaled And Icy",
      album_cover: "https://i.scdn.co/image/ab67616d00001e0220b467550945fd123e00f0a5",
      album_premiere: "2021",
      id: "10",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
      bio: "Twenty One Pilots shook the world with the release of their 2015 LP BLURRYFACE, an album that would go on to sell over 7 million copies worldwide and earn the band their first ever GRAMMY® Award as they shattered longstanding chart records, and captivated audiences worldwide on sold-out arena runs and at international festivals.  Now three years later, the duo of Tyler Joseph and Josh Dun have returned to write the next chapter of their story with TRENCH, the band’s highly anticipated new studio album.  TRENCH finds Twenty One Pilots fearlessly reimagining the possibilities of their music through the same candid expression and genuine identity that helped to cement their place as one of the largest bands in the world.",
      social:{
        instagram: "https://www.instagram.com/twentyonepilots/?theme=dark",
        twitter: "https://twitter.com/twentyonepilots",
        facebook: "https://www.facebook.com/twentyonepilots",
      },
      user_playlist_1: "",
  },
  {
      name: "Mulberry Street",
      artist: "Twenty one pilots",
      src: "TwentyOnePilots-MulberryStreet",
      img: "scaled-and-icy-b-iext104194001",
      style: "Chill",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f22bsf",
      artist_img: "https://i.scdn.co/image/ab6761610000e5eb196972172c37d934d9ca8093",
      album: "Scaled And Icy",
      album_cover: "https://i.scdn.co/image/ab67616d00001e0220b467550945fd123e00f0a5",
      album_premiere: "2021",
      id: "11",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
      bio: "Twenty One Pilots shook the world with the release of their 2015 LP BLURRYFACE, an album that would go on to sell over 7 million copies worldwide and earn the band their first ever GRAMMY® Award as they shattered longstanding chart records, and captivated audiences worldwide on sold-out arena runs and at international festivals.  Now three years later, the duo of Tyler Joseph and Josh Dun have returned to write the next chapter of their story with TRENCH, the band’s highly anticipated new studio album.  TRENCH finds Twenty One Pilots fearlessly reimagining the possibilities of their music through the same candid expression and genuine identity that helped to cement their place as one of the largest bands in the world.",
      social:{
        instagram: "https://www.instagram.com/twentyonepilots/?theme=dark",
        twitter: "https://twitter.com/twentyonepilots",
        facebook: "https://www.facebook.com/twentyonepilots",
      },
      user_playlist_1: "",
  },
  {
      name: "Good Day",
      artist: "Twenty one pilots",
      src: "TwentyOnePilots-GoodDay",
      img: "scaled-and-icy-b-iext104194001",
      style: "Chill",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f22bsf",
      artist_img: "https://i.scdn.co/image/ab6761610000e5eb196972172c37d934d9ca8093",
      album: "Scaled And Icy",
      album_cover: "https://i.scdn.co/image/ab67616d00001e0220b467550945fd123e00f0a5",
      album_premiere: "2021",
      id: "12",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
      bio: "Twenty One Pilots shook the world with the release of their 2015 LP BLURRYFACE, an album that would go on to sell over 7 million copies worldwide and earn the band their first ever GRAMMY® Award as they shattered longstanding chart records, and captivated audiences worldwide on sold-out arena runs and at international festivals.  Now three years later, the duo of Tyler Joseph and Josh Dun have returned to write the next chapter of their story with TRENCH, the band’s highly anticipated new studio album.  TRENCH finds Twenty One Pilots fearlessly reimagining the possibilities of their music through the same candid expression and genuine identity that helped to cement their place as one of the largest bands in the world.",
      social:{
        instagram: "https://www.instagram.com/twentyonepilots/?theme=dark",
        twitter: "https://twitter.com/twentyonepilots",
        facebook: "https://www.facebook.com/twentyonepilots",
      },
      user_playlist_1: "",
  },
  {
      name: "Kłótnia",
      artist: "Evtis",
      src: "Evtis-Kłótnia",
      img: "C-BooL-NeverGoAway",
      style: "Hip-Hop",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f106bsf",
      artist_img: "https://i.scdn.co/image/ab6761610000e5eb76a19046d32c54e79affd6a1",
      album: "Głosy",
      album_cover: "https://i.scdn.co/image/ab6761610000e5eb76a19046d32c54e79affd6a1",
      album_premiere: "2013",
      id: "13",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
      bio: "",
      social:{
        instagram: "",
        twitter: "",
        facebook: "https://www.facebook.com/Evtis",
      },
      user_playlist_1: "",
  },
  {
      name: "Idziemy Po Swoje",
      artist: "Szusty",
      src: "donGURALesko-IdziemyPoSwojeSzUstyBlend",
      img: "guralsko",
      style: "Workout",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f46bsf",
      artist_img: "https://i.scdn.co/image/ab6761610000e5eb4b346794a19f7adfcc244ee7",
      album: "Idziemy Po Swoje",
      album_cover: "https://i.scdn.co/image/ab67616d0000b273dd559af8356ea6b28a71a5fe",
      album_premiere: "2009",
      id: "14",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
      bio: "",
      social:{
        instagram: "https://www.instagram.com/szustyszesc/",
        twitter: "",
        facebook: "https://www.facebook.com/szustyblend",
      },
      user_playlist_1: "",
  },
  {
      name: "Legenda",
      artist: "Szusty",
      src: "donGURALesko-LegendaSzUstyBlend",
      img: "guralsko",
      style: "Workout",
      status: "nostatus",
      tag: "Popular",
      avatar: "41aeb62f0-c2321-f46bsf",
      artist_img: "https://i.scdn.co/image/ab6761610000e5eb4b346794a19f7adfcc244ee7",
      album: "Legenda",
      album_cover: "https://i.scdn.co/image/ab67616d00001e0259b80ddc896cb493dc68e697",
      album_premiere: "2010",
      id: "15",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
      bio: "",
      social:{
        instagram: "https://www.instagram.com/szustyszesc/",
        twitter: "",
        facebook: "https://www.facebook.com/szustyblend",
      },
      user_playlist_1: "",
  },
  {
    name: "Rockstar",
    artist: "Post Malone",
    src: "PostMalone-Rockstar",
    img: "rockstar-w-iext111232885",
    style: "Pop",
    status: "nostatus",
    tag: "Popular",
    avatar: "41aeb62f0=c2321-f23bsf",
    artist_img: "https://i.scdn.co/image/ab6761610000e5ebb894ef9fa437b0389c5567cc",
    album: "beerbongs & bentleys",
    album_cover: "https://i.scdn.co/image/ab67616d00001e02b1c4b76e23414c9f20242268",
    album_premiere: "2018",
    id: "16",
    lyrics:{
      lyrics_verse_1: "",
      lyrics_verse_2: "",
      lyrics_verse_3: "",
      lyrics_verse_4: "",
      lyrics_verse_5: "",
      lyrics_verse_6: "",
      lyrics_verse_7: "",
      lyrics_verse_8: "",
      lyrics_verse_9: "",
      lyrics_verse_10: "",
      lyrics_verse_11: "",
      lyrics_verse_12: "",
      lyrics_verse_13: "",
      lyrics_verse_14: ""
    },
    bio: "In 2016, he released the single Go Flex along with his official debut mixtape, August 26th. Months later, his first studio effort arrived. Stoney featured guests ranging from ",
    social:{
      instagram: "https://www.instagram.com/postmalone/",
      twitter: "https://twitter.com/postmalone",
      facebook: "https://www.facebook.com/postmalone",
    },
    user_playlist_1: "",
  },
  {
    name: "Bez Znieczulenia",
    artist: "Happysad",
    src: "Happysad-Bezznieczulenia",
    img: "ab67616d00001e021f86dffe512418a230887e69",
    style: "Rock",
    status: "nostatus",
    avatar: "14235843737BeNz9sRRfK4jsYeLQ7t32Pg76m86w",
    artist_img: "https://i.scdn.co/image/ab6761610000e5ebd6e4988f56f08add19e0dd7b",
    album: "Mów mi dobrze",
    album_cover: "https://i.scdn.co/image/ab67616d00001e021f86dffe512418a230887e69",
    album_premiere: "2009",
    id: "17",
    lyrics:{
      lyrics_verse_1: "",
      lyrics_verse_2: "",
      lyrics_verse_3: "",
      lyrics_verse_4: "",
      lyrics_verse_5: "",
      lyrics_verse_6: "",
      lyrics_verse_7: "",
      lyrics_verse_8: "",
      lyrics_verse_9: "",
      lyrics_verse_10: "",
      lyrics_verse_11: "",
      lyrics_verse_12: "",
      lyrics_verse_13: "",
      lyrics_verse_14: ""
    },
    bio: "Originating in Skarżysko-Kamienna in 2001, Happysad is a popular Polish rock band distinguished by friendly melodies and reggae-influenced rhythms. Their debut album, Wszystko Jedno, was issued by ",
    social:{
      instagram: "https://www.instagram.com/happysadpl",
      twitter: "",
      facebook: "https://www.facebook.com/happysadpl",
    },
    user_playlist_1: "",
  },
  {
    name: "Pętla",
    artist: "Happysad",
    src: "Happysad-Pętla",
    img: "ab67616d00001e021f86dffe512418a230887e69",
    style: "Rock",
    status: "nostatus",
    tag: "Popular",
    avatar: "14235843737BeNz9sRRfK4jsYeLQ7t32Pg76m86w",
    artist_img: "https://i.scdn.co/image/ab6761610000e5ebd6e4988f56f08add19e0dd7b",
    album: "Mów mi dobrze",
    album_cover: "https://i.scdn.co/image/ab67616d00001e021f86dffe512418a230887e69",
    album_premiere: "2009",
    id: "18",
    lyrics:{
      lyrics_verse_1: "",
      lyrics_verse_2: "",
      lyrics_verse_3: "",
      lyrics_verse_4: "",
      lyrics_verse_5: "",
      lyrics_verse_6: "",
      lyrics_verse_7: "",
      lyrics_verse_8: "",
      lyrics_verse_9: "",
      lyrics_verse_10: "",
      lyrics_verse_11: "",
      lyrics_verse_12: "",
      lyrics_verse_13: "",
      lyrics_verse_14: ""
    },
    bio: "Originating in Skarżysko-Kamienna in 2001, Happysad is a popular Polish rock band distinguished by friendly melodies and reggae-influenced rhythms. Their debut album, Wszystko Jedno, was issued by ",
    social:{
      instagram: "https://www.instagram.com/happysadpl",
      twitter: "",
      facebook: "https://www.facebook.com/happysadpl",
    },
    user_playlist_1: "",
  },
  {
    name: "Tired Bones",
    artist: "L.B.ONE",
    src: "LBONE-TiredBones",
    img: "tired-bones-w-iext52557958",
    style: "Energic",
    status: "nostatus",
    avatar: "5cd42c454b86e992d288a65bd8a187b62151",
    artist_img: "https://i.scdn.co/image/ab6761610000e5eba6cbc503bf2aca8d539a7f92",
    album: "Lonely",
    album_cover: "https://i.scdn.co/image/ab67616d00001e021a2250d8502746a80d72da8d",
    album_premiere: "2018",
    id: "19",
    lyrics:{
      lyrics_verse_1: "",
      lyrics_verse_2: "",
      lyrics_verse_3: "",
      lyrics_verse_4: "",
      lyrics_verse_5: "",
      lyrics_verse_6: "",
      lyrics_verse_7: "",
      lyrics_verse_8: "",
      lyrics_verse_9: "",
      lyrics_verse_10: "",
      lyrics_verse_11: "",
      lyrics_verse_12: "",
      lyrics_verse_13: "",
      lyrics_verse_14: ""
    },
    bio: "Lianny BOUDJADI (L.B.ONE) is a French Electronic DJ-Producer. In 2017 he produce Across The Water feat Laenz and will be #1 radio charts in Russia and Ukraine. French solo artist most playlisted on eastern countries radio, a second single will follow Tired Bones and will be Number one in 15 eastern countries.",
    social:{
      instagram: "https://www.instagram.com/DJLBONE",
      twitter: "https://twitter.com/DJLBONE",
      facebook: "https://www.facebook.com/djlbone/",
    },
    user_playlist_1: "",
  },
  {
    name: "Złap Za Broń",
    artist: "Trzeci Wymiar",
    src: "TrzeciWymiar-Złapzabroń",
    img: "6341ef2bd3abc2c21c6ee6466cb67d15.510x510x1",
    style: "Hip-Hop",
    status: "nostatus",
    avatar: "41aeb62f0-c2321-f24bsf",
    artist_img: "https://i.scdn.co/image/ab67616d0000b273cb498bab77f77940c83145fa",
    album: "Złodzieje Czasu",
    album_cover: "https://i.scdn.co/image/ab67616d00001e02d922659188234fee83318fe7",
    album_premiere: "2009",
    id: "20",
    lyrics:{
      lyrics_verse_1: "",
      lyrics_verse_2: "",
      lyrics_verse_3: "",
      lyrics_verse_4: "",
      lyrics_verse_5: "",
      lyrics_verse_6: "",
      lyrics_verse_7: "",
      lyrics_verse_8: "",
      lyrics_verse_9: "",
      lyrics_verse_10: "",
      lyrics_verse_11: "",
      lyrics_verse_12: "",
      lyrics_verse_13: "",
      lyrics_verse_14: ""
    },
    bio: "",
    social:{
      instagram: "",
      twitter: "",
      facebook: "",
    },
    user_playlist_1: "",
  },
  {
    name: "I'm Not Rich",
    artist: "The King's Son",
    src: "TheKingsSon-ImNotRich",
    img: "ab67616d0000b27369cdca7b90ca8060e3525196",
    style: "Chill",
    status: "nostatus",
    avatar: "41aeb62f0=c2321-f56bsf",
    artist_img: "https://i.scdn.co/image/2b9dc7ef187414be63e89488aef91f96c3e2170d",
    album: "The King",
    album_cover: "https://i.scdn.co/image/ab67616d00001e02ec999a8391a2dcb970f69cb0",
    album_premiere: "2015",
    id: "21",
    lyrics:{
      lyrics_verse_1: "",
      lyrics_verse_2: "",
      lyrics_verse_3: "",
      lyrics_verse_4: "",
      lyrics_verse_5: "",
      lyrics_verse_6: "",
      lyrics_verse_7: "",
      lyrics_verse_8: "",
      lyrics_verse_9: "",
      lyrics_verse_10: "",
      lyrics_verse_11: "",
      lyrics_verse_12: "",
      lyrics_verse_13: "",
      lyrics_verse_14: ""
    },
    bio: "",
    social:{
      instagram: "",
      twitter: "",
      facebook: "",
    },
    user_playlist_1: "",
  },
  {
    name: "Invincible",
    artist: "MGK",
    src: "MGK-Invincible",
    img: "ab67616d0000b273a57d3a2736f815d3cf358e37",
    style: "Workout",
    status: "nostatus",
    avatar: "41aeb62f0=c2321-f57bsf",
    artist_img: "https://i.scdn.co/image/ab6761610000e5eb1fd54eb6e30d0bc8f633621e",
    album: "Start, GO",
    album_cover: "https://i.scdn.co/image/ab67616d0000b273cfac68443715de902bd7ea53",
    album_premiere: "2012",
    id: "22",
    lyrics:{
      lyrics_verse_1: "",
      lyrics_verse_2: "",
      lyrics_verse_3: "",
      lyrics_verse_4: "",
      lyrics_verse_5: "",
      lyrics_verse_6: "",
      lyrics_verse_7: "",
      lyrics_verse_8: "",
      lyrics_verse_9: "",
      lyrics_verse_10: "",
      lyrics_verse_11: "",
      lyrics_verse_12: "",
      lyrics_verse_13: "",
      lyrics_verse_14: ""
    },
    bio: "Delivering lyrics with the speed of a bullet train, Cleveland rapper Machine Gun Kelly experienced a meteoric rise in late 2011 when he transitioned from grinding out self-released mixtapes to working with major labels. From there, the rapper skyrocketed to superstar status, with each of his albums charting in the Top Ten. A beef with , a film career, and even some reality show appearances would follow as the high-powered lyrical rap style of albums like 2019's Hotel Diablo morphed into a driving emo-rock sound on collaborations with  and on the -produced 2020 album Tickets to My Downfall, which topped the Billboard 200. Kelly worked alongside  again in 2022 on album number six, Mainstream Sellout.",
    social:{
      instagram: "https://www.instagram.com/machinegunkelly/",
      twitter: "https://twitter.com/machinegunkelly",
      facebook: "https://www.facebook.com/machinegunkellymusic",
    },
    user_playlist_1: "",
  },
  {
    name: "In The Name Of Love",
    artist: "Bebe Rexha",
    src: "BebeRexha-InTheNameOfLove",
    img: "ab67616d0000b2738c77bcf5f5a227d270d23370",
    style: "Energic",
    status: "nostatus",
    tag: "Popular",
    avatar: "41aeb62f0=c2321-f58bsf",
    artist_img: "https://i.scdn.co/image/ab6761610000e5ebabfac786f093c4da55c99d4e",
    album: "In The Name Of Love",
    album_cover: "https://i.scdn.co/image/ab67616d0000b2738c77bcf5f5a227d270d23370",
    album_premiere: "2016",
    id: "23",
    lyrics:{
      lyrics_verse_1: "",
      lyrics_verse_2: "",
      lyrics_verse_3: "",
      lyrics_verse_4: "",
      lyrics_verse_5: "",
      lyrics_verse_6: "",
      lyrics_verse_7: "",
      lyrics_verse_8: "",
      lyrics_verse_9: "",
      lyrics_verse_10: "",
      lyrics_verse_11: "",
      lyrics_verse_12: "",
      lyrics_verse_13: "",
      lyrics_verse_14: ""
    },
    bio: "Rising as a songwriter for and , Brooklyn-born Bebe Rexha made her way from the studio to the stage, racking up hit singles with electronic artists (, , ), rappers (, , ), and even country duo , with whom she recorded the 2017 chart-topping country-pop crossover single Meant to Be. Although her work with other musicians has spanned genres, her own material centers on darker pop textures influenced by hip-hop and R&B, as heard on her debut, 2018's Expectations, and its 2021 follow-up Better Mistakes. Born Bleta Rexha in 1989, she began her musical journey at a young age. Performing in musicals from the age of four, she started to hone her skills in her early teens and was named Best Teen Songwriter at the National Academy of Recording Arts and Sciences annual Grammy Day event; she met a whole host of famous producers there. In 2010, Rexha was approached bys  to form the project , intended to reflects more experimental and electronic side. Rexha provided vocals for several EPs before she left the band in 2012 to embark on a solo career. She began uploading demos and acoustic covers to YouTube before signing with  in 2013.",
    social:{
      instagram: "https://www.instagram.com/beberexha",
      twitter: "https://twitter.com/beberexha",
      facebook: "https://www.facebook.com/beberexha",
    },
    user_playlist_1: "",
  },
  {
    name: "One Last Time",
    artist: "Ariana Grande",
    src: "ArianaGrande-OneLastTime",
    img: "e63468347c14c9f580857daae877a005",
    style: "Energic",
    status: "nostatus",
    tag: "Popular",
    avatar: "ab67616d30590b273a25d3a2736f815d3cf358e37",
    artist_img: "https://i.scdn.co/image/ab6761610000e5ebcdce7620dc940db079bf4952",
    album: "Me Everything",
    album_cover: "https://i.scdn.co/image/ab67616d00001e02deec12a28d1e336c5052e9aa",
    album_premiere: "2014",
    id: "24",
    lyrics:{
      lyrics_verse_1: "",
      lyrics_verse_2: "",
      lyrics_verse_3: "",
      lyrics_verse_4: "",
      lyrics_verse_5: "",
      lyrics_verse_6: "",
      lyrics_verse_7: "",
      lyrics_verse_8: "",
      lyrics_verse_9: "",
      lyrics_verse_10: "",
      lyrics_verse_11: "",
      lyrics_verse_12: "",
      lyrics_verse_13: "",
      lyrics_verse_14: ""
    },
    bio: "Ariana Grande is perhaps the quintessential pop star of the last half of the 2010s, capturing the era's spirit and style. Emerging in 2013 with the hit single The Way, Grande initially appeared to be the heir to the throne of , due in part to her powerhouse vocals. With its  production, her debut Yours Truly underscored her debt to '90s R&B, but Grande quickly incorporated hip-hop and EDM into her music.",
    social:{
      instagram: "https://www.instagram.com/arianagrande/",
      twitter: "",
      facebook: "https://www.facebook.com/arianagrande",
    },
    user_playlist_1: "",
  },
]
