var allMusic = [

  {
      name: "Havana",
      artist: "Camila Cabello",
      colaboration: "",
      artist_status: "none",

      src: "CamilaCabelloHavana",
      img: "CamilaCabelloHavana",
      style: "Energic",
      status: "nostatus",
      tag: "Popular",
      avatar: "41aeb62f0-c2321-f45bsf",
      artist_img: "https://i.scdn.co/image/ab6761610000e5ebec05963eab63676a539fef13",
      gallery_img_1: "https://pbs.twimg.com/media/FfYo9bUWIAI3pNq?format=jpg&name=large",
      gallery_img_2: "https://pbs.twimg.com/media/FfYo9bUX0AAtOz5?format=jpg&name=large",
      gallery_img_3: "https://pbs.twimg.com/media/FaF-EVDX0AIk-g2?format=jpg&name=medium",
      gallery_img_4: "https://pbs.twimg.com/media/FY4Gs0gWYAEoXos?format=jpg&name=large",
      gallery_img_5: "https://pbs.twimg.com/media/FUgIUrvXEAIZHHk?format=jpg&name=large",

      album: "Camila",
      album_cover: "https://i.scdn.co/image/ab67616d00001e026eb0b9e73adcf04e4ed3eca4",
      album_premiere: "2018",
      id: "0",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
      bio: "Multi-Grammy nominated Cuban born singer/songwriter Camila Cabello released her debut solo album, CAMILA in January 2018 to rave reviews. It debuted at #1 on the Billboard 200 chart at the same time as her single “Havana” reached #1 on the Billboard Hot 100 chart, making her the first solo artist in nearly 15 years to reach the #1 spot on the Hot 100, Billboard 200 & Artist 100 charts in the same week. CAMILA launched its debut at #1 on 110 iTunes charts around the world, breaking the record for most #1 positions for a debut album in iTunes history. Camila also became the #1 artist on global Spotify. She released her RIAA 9x platinum smash hit “Havana,” in August 2017 where it obtained the #1 spot on the pop radio chart. “Havana” is the first song by a female artist to reach No. 1 on Billboard’s Adult Contemporary, Pop Songs & Rhythmic Songs charts in 22 years, has earned over 1.1 billion on-demand U.S. streams, according to Nielsen Music, & attained the longest run at No. 1 on Pop Songs for any song by a female artist since 2013. Havana became the most streamed song of all time by a female artist & was the number one song of 2018 globally. Her triple-platinum single “Never Be The Same,” was released in January 2018 & peaked in the top 10 of the Billboard Hot 100 chart. Camila became the first artist in history to have two multi-format number one singles as the first two singles from their debut album. In November 2018, she was named the new ambassador for Save the Children.",
      social:{
        instagram: "https://www.instagram.com/camila_cabello/",
        twitter: "https://twitter.com/camila_cabello",
        facebook: "https://www.facebook.com/camilacabello",
      },
      user_playlist_1: "",
  },
  {
      name: "Dj Is Your Second Name",
      artist: "C-Bool",
      colaboration: "Giang Pham",
      artist_status: "none",
      
      src: "C-BooLDJ",
      img: "C-BooLDJ",
      style: "Energic",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f25bsf",
      artist_img: "https://i.scdn.co/image/ab6761610000e5eb00a89c0f54687319c9a499de",
      gallery_img_1: "https://pbs.twimg.com/media/Dy4FILeWoAAIqn8?format=jpg&name=large",
      gallery_img_2: "https://pbs.twimg.com/media/D7Bd4x5UIAIQ4IJ?format=jpg&name=900x900",
      gallery_img_3: "https://pbs.twimg.com/media/FFnM392XEA0h-YH?format=jpg&name=large",
      gallery_img_4: "",
      gallery_img_5: "",

      album: "Dj Is Your Second Name",
      album_cover: "https://i.scdn.co/image/ab67616d0000b2734470a94060697a4265fb0e03",
      album_premiere: "2017",
      id: "1",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
      bio: "C-BooL (Grzegorz Cebula) was born on May 30, 1981 in Pyskowice in Silesia (Poland). Polish DJ, music producer and owner of C-Wave Records. Associated with club music from an early age. Works as a DJ since 1998 and started producing music in 2002. Diamond, multi platinum and golden records producer of many radio hits like Never Go Away, DJ Is Your Second Name, Magic Symphony, Wonderland, Catch You, Fire In My Head, La La Love and older club classics like Would You Feel and House Baby. Two-time winner of the Eska Music Awards in the hit of the year category (2016 & 2017). No 1 Hits - Shazam Poland, Radio Airplay Poland Top 3 Hits Airplay Russia In his 23-year DJ career C-BooL performed in hundreds of clubs in Poland and abroad. His DJ sets were presented in countries such as Germany, Austria, Italy, Bulgaria & UK",
      social:{
        instagram: "",
        twitter: "",
        facebook: "https://www.facebook.com/cboolmusic",
      },
      user_playlist_1: "",
  },
  {
      name: "Never Go Away",
      artist: "C-Bool",
      colaboration: "Giang Pham",
      artist_status: "none",

      src: "C-BooL-NeverGoAway",
      img: "C-BooL-NeverGoAway",
      style: "Energic",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f25bsf",
      artist_img: "https://pbs.twimg.com/media/Dy4FBQjWwAYVQPm?format=jpg&name=large",
      gallery_img_1: "https://pbs.twimg.com/media/Dy4FILeWoAAIqn8?format=jpg&name=large",
      gallery_img_2: "https://pbs.twimg.com/media/D7Bd4x5UIAIQ4IJ?format=jpg&name=900x900",
      gallery_img_3: "https://pbs.twimg.com/media/FFnM392XEA0h-YH?format=jpg&name=large",
      gallery_img_4: "",
      gallery_img_5: "",

      album: "Never Go Away",
      album_cover: "https://i.scdn.co/image/ab67616d00001e0225a6f8a62f4d061ef61169c9",
      album_premiere: "2016",
      id: "2",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
      bio: "C-BooL (Grzegorz Cebula) was born on May 30, 1981 in Pyskowice in Silesia (Poland). Polish DJ, music producer and owner of C-Wave Records. Associated with club music from an early age. Works as a DJ since 1998 and started producing music in 2002. Diamond, multi platinum and golden records producer of many radio hits like Never Go Away, DJ Is Your Second Name, Magic Symphony, Wonderland, Catch You, Fire In My Head, La La Love and older club classics like Would You Feel and House Baby. Two-time winner of the Eska Music Awards in the hit of the year category (2016 & 2017). No 1 Hits - Shazam Poland, Radio Airplay Poland Top 3 Hits Airplay Russia In his 23-year DJ career C-BooL performed in hundreds of clubs in Poland and abroad. His DJ sets were presented in countries such as Germany, Austria, Italy, Bulgaria & UK",
      social:{
        instagram: "",
        twitter: "",
        facebook: "https://www.facebook.com/cboolmusic",
      },
      user_playlist_1: "",
  },
  {
      name: "Champions",
      artist: "Kevin Rudolf",
      colaboration: "",
      artist_status: "none",

      src: "KevinRudolf-Champions",
      img: "KevinRudolf-Champions",
      style: "Workout",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f31bsf",
      artist_img: "https://i.scdn.co/image/ab6761610000e5ebf977eaad9f10f82d6b3e3278",
      gallery_img_1: "https://pbs.twimg.com/media/Etwk22iVcAM19AW?format=jpg&name=small",
      gallery_img_2: "https://pbs.twimg.com/media/EV02yJoWsAI_X8u?format=jpg&name=900x900",
      gallery_img_3: "",
      gallery_img_4: "",
      gallery_img_5: "",

      album: "Champions",
      album_cover: "https://i.scdn.co/image/ab67616d00001e02335815746144562adb8455b4",
      album_premiere: "2012",
      id: "3",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
      bio: "A rocker running in rap circles, singer/songwriter/producer Kevin Rudolf worked on multiple hit songs before making his own bid for stardom as the first rock artist signed to rap label",
      social:{
        instagram: "https://www.instagram.com/kevinrudolf/?theme=dark",
        twitter: "https://twitter.com/kevinrudolf",
        facebook: "https://www.facebook.com/kevinrudolf/?eid=ARDXHcejUXCfQ99mrwayQUj_NWr41eTSTGWFhdYz-QCptcsP-JGRWgapKE7Cgfs8GlZ6wa9UK7Cud_oO",
      },
      user_playlist_1: "",
  },
  {
      name: "Ride It",
      artist: "DJ Regard",
      colaboration: "",
      artist_status: "none",

      src: "DJRegard-Rideit",
      img: "DJRegard-Rideit",
      style: "Energic",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f21bsf",
      artist_img: "https://i.scdn.co/image/ab6761610000e5ebf2463642042d6e99c687b42c",
      gallery_img_1: "https://pbs.twimg.com/media/FAW4wAhVgAAm1BD?format=jpg&name=large",
      gallery_img_2: "https://pbs.twimg.com/media/E8Wg9uHXMAYtKbh?format=jpg&name=medium",
      gallery_img_3: "",
      gallery_img_4: "",
      gallery_img_5: "",
      
      album: "Ride It",
      album_cover: "https://i.scdn.co/image/ab67616d00001e025c27813ae019011fcb370c78",
      album_premiere: "2019",
      id: "4",
      lyrics:{
        lyrics_verse_1: "Just lose control Ride it, ride it, come touch my soul Ride it, ride it, let me feel you Ride it, turn the lights down low Ride it, from head to toe Ride it, ride it, come touch my soul Ride it, ride it, let me feel you",
        lyrics_verse_2: "It's been a month and twenty days And we're going 'round and 'round, playing silly games Now you're saying, slow it down, not right now Then you wink at me and walk away Let it be, let it be, let it be known Hold on, don't go Touching and teasing me, telling me no But this time I need to feel you",
        lyrics_verse_3: "Ride it, we're all alone Ride it, just lose control Ride it, ride it, come touch my soul Ride it, ride it, let me feel you Ride it, turn the lights down low Ride it, from head to toe Ride it, ride it, come touch my soul Ride it, ride it, let me feel you",
        lyrics_verse_4: "Movida was the club on the Saturday You're actin' like a diva, sayin' you don't wanna pay It's gotta be ya feisty style, raised eyebrow I love it when you look at me that way Now we're in, you order a mojito at the bar Re-apply your lippy 'cause it came off on the glass The DJ plays your favorite song, Kanye's on Now ya beckoning for me to dance Mm, pullin' me, pullin' me, pullin' me close Just close your eyes, girl Whispering, tellin' me, we gotta go Won't you take me home? I wanna",
        lyrics_verse_5: "Ride it, we're all alone Ride it, just lose control Ride it, ride it, come touch my soul Ride it, ride it, let me feel you Ride it, turn the lights down low Ride it, from head to toe Ride it, ride it, come touch my soul Ride it, ride it, let me feel you",
        lyrics_verse_6: "Ride it, we're all alone Ride it, just lose control Ride it, ride it, come touch my soul Ride it, ride it, let me feel you Ride it, turn the lights down low Ride it, from head to toe Ride it, ride it, come touch my soul Ride it, ride it, let me feel you",
        lyrics_verse_7: "Won't you take me home? I wanna, Ride it, we're all alone Ride it, just lose control Ride it, ride it, come touch my soul Ride it, ride it, let me feel you Ride it, turn the lights down low Ride it, from head to toe Ride it, ride it, come touch my soul Ride it, ride it, let me feel you",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
      bio: "Kosovan DJ & Producer Regard built up over 1 million Subscribers through his series of deep house mixes, remixes and original tracks in support of LEAF Management signed since of 2012. In July 2019 Regard released his first official single 'Ride It' in the other label at Ministry of Sound and managed by LEAF Management. 'Ride It' became an international hit, taking the internet and TikTok by storm, achieving over ten top 10 single chart placements globally, including #2 in the UK where 'Ride It' is now Certified Multi-Platinum. Regard finished the 'Ride It' campaign with an amazing debut at Capital's Jingle Bell Ball, and on his first TV performance in UK at Top of The Pops. Regard remixing Dua Lipa's hit 'Don't Start Me Now at February. Regard has released the latest record 'Secrets' featuring with Raye by the end of April, while it's running very well as second record by Regard. Regard contacts: ",
      social:{
        instagram: "https://www.instagram.com/djregardofficial/?theme=dark",
        twitter: "https://twitter.com/DardanRegard",
        facebook: "https://www.facebook.com/DjRegardOfficial/",
      },
      user_playlist_1: "",
  },
  {
      name: "Choker",
      artist: "Twenty one pilots",
      colaboration: "",
      artist_status: "none",

      src: "twentyonepilots-Choker",
      img: "scaled-and-icy-b-iext104194001",
      style: "Chill",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f22bsf",
      artist_img: "https://i.scdn.co/image/ab6761610000e5eb196972172c37d934d9ca8093",
      gallery_img_1: "https://pbs.twimg.com/media/FfeDi8NVEAAcBE0?format=jpg&name=large",
      gallery_img_2: "https://pbs.twimg.com/media/FfeDi8JUYAAjoTF?format=jpg&name=large",
      gallery_img_3: "https://pbs.twimg.com/media/FdSJa6yUAAErdk0?format=jpg&name=large",
      gallery_img_4: "https://pbs.twimg.com/media/FdSJa6xVEAAelRv?format=jpg&name=large",
      gallery_img_5: "https://pbs.twimg.com/media/FcpomMVX0AoD7Bx?format=jpg&name=large",
      
      album: "Scaled And Icy",
      album_cover: "https://i.scdn.co/image/ab67616d00001e0220b467550945fd123e00f0a5",
      album_premiere: "2021",
      id: "5",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
      bio: "Twenty One Pilots shook the world with the release of their 2015 LP BLURRYFACE, an album that would go on to sell over 7 million copies worldwide and earn the band their first ever GRAMMY® Award as they shattered longstanding chart records, and captivated audiences worldwide on sold-out arena runs and at international festivals.  Now three years later, the duo of Tyler Joseph and Josh Dun have returned to write the next chapter of their story with TRENCH, the band’s highly anticipated new studio album.  TRENCH finds Twenty One Pilots fearlessly reimagining the possibilities of their music through the same candid expression and genuine identity that helped to cement their place as one of the largest bands in the world.",
      social:{
        instagram: "https://www.instagram.com/twentyonepilots/?theme=dark",
        twitter: "https://twitter.com/twentyonepilots",
        facebook: "https://www.facebook.com/twentyonepilots",
      },
      user_playlist_1: "",
  },
  {
      name: "The Outside",
      artist: "Twenty one pilots",
      colaboration: "",
      artist_status: "none",

      src: "TwentyOnePilots-TheOutside",
      img: "scaled-and-icy-b-iext104194001",
      style: "Chill",
      status: "nostatus",
      tag: "Popular",
      avatar: "41aeb62f0-c2321-f22bsf",
      artist_img: "https://i.scdn.co/image/ab6761610000e5eb196972172c37d934d9ca8093",
      gallery_img_1: "https://pbs.twimg.com/media/FfeDi8NVEAAcBE0?format=jpg&name=large",
      gallery_img_2: "https://pbs.twimg.com/media/FfeDi8JUYAAjoTF?format=jpg&name=large",
      gallery_img_3: "https://pbs.twimg.com/media/FdSJa6yUAAErdk0?format=jpg&name=large",
      gallery_img_4: "https://pbs.twimg.com/media/FdSJa6xVEAAelRv?format=jpg&name=large",
      gallery_img_5: "https://pbs.twimg.com/media/FcpomMVX0AoD7Bx?format=jpg&name=large",
      
      album: "Scaled And Icy",
      album_cover: "https://i.scdn.co/image/ab67616d00001e0220b467550945fd123e00f0a5",
      album_premiere: "2021",
      id: "6",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
      bio: "Twenty One Pilots shook the world with the release of their 2015 LP BLURRYFACE, an album that would go on to sell over 7 million copies worldwide and earn the band their first ever GRAMMY® Award as they shattered longstanding chart records, and captivated audiences worldwide on sold-out arena runs and at international festivals.  Now three years later, the duo of Tyler Joseph and Josh Dun have returned to write the next chapter of their story with TRENCH, the band’s highly anticipated new studio album.  TRENCH finds Twenty One Pilots fearlessly reimagining the possibilities of their music through the same candid expression and genuine identity that helped to cement their place as one of the largest bands in the world.",
      social:{
        instagram: "https://www.instagram.com/twentyonepilots/?theme=dark",
        twitter: "https://twitter.com/twentyonepilots",
        facebook: "https://www.facebook.com/twentyonepilots",
      },
      user_playlist_1: "",
  },
  {
      name: "Shy Away",
      artist: "Twenty one pilots",
      colaboration: "",
      artist_status: "none",

      src: "TwentyOnePilots-ShyAway",
      img: "scaled-and-icy-b-iext104194001",
      style: "Chill",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f22bsf",
      artist_img: "https://i.scdn.co/image/ab6761610000e5eb196972172c37d934d9ca8093",
      gallery_img_1: "https://pbs.twimg.com/media/FfeDi8NVEAAcBE0?format=jpg&name=large",
      gallery_img_2: "https://pbs.twimg.com/media/FfeDi8JUYAAjoTF?format=jpg&name=large",
      gallery_img_3: "https://pbs.twimg.com/media/FdSJa6yUAAErdk0?format=jpg&name=large",
      gallery_img_4: "https://pbs.twimg.com/media/FdSJa6xVEAAelRv?format=jpg&name=large",
      gallery_img_5: "https://pbs.twimg.com/media/FcpomMVX0AoD7Bx?format=jpg&name=large",
      
      album: "Scaled And Icy",
      album_cover: "https://i.scdn.co/image/ab67616d00001e0220b467550945fd123e00f0a5",
      album_premiere: "2021",
      id: "7",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
      bio: "Twenty One Pilots shook the world with the release of their 2015 LP BLURRYFACE, an album that would go on to sell over 7 million copies worldwide and earn the band their first ever GRAMMY® Award as they shattered longstanding chart records, and captivated audiences worldwide on sold-out arena runs and at international festivals.  Now three years later, the duo of Tyler Joseph and Josh Dun have returned to write the next chapter of their story with TRENCH, the band’s highly anticipated new studio album.  TRENCH finds Twenty One Pilots fearlessly reimagining the possibilities of their music through the same candid expression and genuine identity that helped to cement their place as one of the largest bands in the world.",
      social:{
        instagram: "https://www.instagram.com/twentyonepilots/?theme=dark",
        twitter: "https://twitter.com/twentyonepilots",
        facebook: "https://www.facebook.com/twentyonepilots",
      },
      user_playlist_1: "",
  },
  {
      name: "Saturday",
      artist: "Twenty one pilots",
      colaboration: "",
      artist_status: "none",

      src: "TwentyOnePilots-Saturday",
      img: "scaled-and-icy-b-iext104194001",
      style: "Chill",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f22bsf",
      artist_img: "https://i.scdn.co/image/ab6761610000e5eb196972172c37d934d9ca8093",
      gallery_img_1: "https://pbs.twimg.com/media/FfeDi8NVEAAcBE0?format=jpg&name=large",
      gallery_img_2: "https://pbs.twimg.com/media/FfeDi8JUYAAjoTF?format=jpg&name=large",
      gallery_img_3: "https://pbs.twimg.com/media/FdSJa6yUAAErdk0?format=jpg&name=large",
      gallery_img_4: "https://pbs.twimg.com/media/FdSJa6xVEAAelRv?format=jpg&name=large",
      gallery_img_5: "https://pbs.twimg.com/media/FcpomMVX0AoD7Bx?format=jpg&name=large",
      
      album: "Scaled And Icy",
      album_cover: "https://i.scdn.co/image/ab67616d00001e0220b467550945fd123e00f0a5",
      album_premiere: "2021",
      id: "8",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
      bio: "Twenty One Pilots shook the world with the release of their 2015 LP BLURRYFACE, an album that would go on to sell over 7 million copies worldwide and earn the band their first ever GRAMMY® Award as they shattered longstanding chart records, and captivated audiences worldwide on sold-out arena runs and at international festivals.  Now three years later, the duo of Tyler Joseph and Josh Dun have returned to write the next chapter of their story with TRENCH, the band’s highly anticipated new studio album.  TRENCH finds Twenty One Pilots fearlessly reimagining the possibilities of their music through the same candid expression and genuine identity that helped to cement their place as one of the largest bands in the world.",
      social:{
        instagram: "https://www.instagram.com/twentyonepilots/?theme=dark",
        twitter: "https://twitter.com/twentyonepilots",
        facebook: "https://www.facebook.com/twentyonepilots",
      },
      user_playlist_1: "",
  },
  {
      name: "Redecorate",
      artist: "Twenty one pilots",
      colaboration: "",
      artist_status: "none",

      src: "TwentyOnePilots-Redecorate",
      img: "scaled-and-icy-b-iext104194001",
      style: "Chill",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f22bsf",
      artist_img: "https://i.scdn.co/image/ab6761610000e5eb196972172c37d934d9ca8093",
      gallery_img_1: "https://pbs.twimg.com/media/FfeDi8NVEAAcBE0?format=jpg&name=large",
      gallery_img_2: "https://pbs.twimg.com/media/FfeDi8JUYAAjoTF?format=jpg&name=large",
      gallery_img_3: "https://pbs.twimg.com/media/FdSJa6yUAAErdk0?format=jpg&name=large",
      gallery_img_4: "https://pbs.twimg.com/media/FdSJa6xVEAAelRv?format=jpg&name=large",
      gallery_img_5: "https://pbs.twimg.com/media/FcpomMVX0AoD7Bx?format=jpg&name=large",
      
      album: "Scaled And Icy",
      album_cover: "https://i.scdn.co/image/ab67616d00001e0220b467550945fd123e00f0a5",
      album_premiere: "2021",
      id: "9",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
      bio: "Twenty One Pilots shook the world with the release of their 2015 LP BLURRYFACE, an album that would go on to sell over 7 million copies worldwide and earn the band their first ever GRAMMY® Award as they shattered longstanding chart records, and captivated audiences worldwide on sold-out arena runs and at international festivals.  Now three years later, the duo of Tyler Joseph and Josh Dun have returned to write the next chapter of their story with TRENCH, the band’s highly anticipated new studio album.  TRENCH finds Twenty One Pilots fearlessly reimagining the possibilities of their music through the same candid expression and genuine identity that helped to cement their place as one of the largest bands in the world.",
      social:{
        instagram: "https://www.instagram.com/twentyonepilots/?theme=dark",
        twitter: "https://twitter.com/twentyonepilots",
        facebook: "https://www.facebook.com/twentyonepilots",
      },
      user_playlist_1: "",
  },
  {
      name: "Never Take It",
      artist: "Twenty one pilots",
      colaboration: "",
      artist_status: "none",

      src: "TwentyOnePilots-NeverTakeIt",
      img: "scaled-and-icy-b-iext104194001",
      style: "Chill",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f22bsf",
      artist_img: "https://i.scdn.co/image/ab6761610000e5eb196972172c37d934d9ca8093",
      gallery_img_1: "https://pbs.twimg.com/media/FfeDi8NVEAAcBE0?format=jpg&name=large",
      gallery_img_2: "https://pbs.twimg.com/media/FfeDi8JUYAAjoTF?format=jpg&name=large",
      gallery_img_3: "https://pbs.twimg.com/media/FdSJa6yUAAErdk0?format=jpg&name=large",
      gallery_img_4: "https://pbs.twimg.com/media/FdSJa6xVEAAelRv?format=jpg&name=large",
      gallery_img_5: "https://pbs.twimg.com/media/FcpomMVX0AoD7Bx?format=jpg&name=large",
      
      album: "Scaled And Icy",
      album_cover: "https://i.scdn.co/image/ab67616d00001e0220b467550945fd123e00f0a5",
      album_premiere: "2021",
      id: "10",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
      bio: "Twenty One Pilots shook the world with the release of their 2015 LP BLURRYFACE, an album that would go on to sell over 7 million copies worldwide and earn the band their first ever GRAMMY® Award as they shattered longstanding chart records, and captivated audiences worldwide on sold-out arena runs and at international festivals.  Now three years later, the duo of Tyler Joseph and Josh Dun have returned to write the next chapter of their story with TRENCH, the band’s highly anticipated new studio album.  TRENCH finds Twenty One Pilots fearlessly reimagining the possibilities of their music through the same candid expression and genuine identity that helped to cement their place as one of the largest bands in the world.",
      social:{
        instagram: "https://www.instagram.com/twentyonepilots/?theme=dark",
        twitter: "https://twitter.com/twentyonepilots",
        facebook: "https://www.facebook.com/twentyonepilots",
      },
      user_playlist_1: "",
  },
  {
      name: "Mulberry Street",
      artist: "Twenty one pilots",
      colaboration: "",
      artist_status: "none",

      src: "TwentyOnePilots-MulberryStreet",
      img: "scaled-and-icy-b-iext104194001",
      style: "Chill",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f22bsf",
      artist_img: "https://i.scdn.co/image/ab6761610000e5eb196972172c37d934d9ca8093",
      gallery_img_1: "https://pbs.twimg.com/media/FfeDi8NVEAAcBE0?format=jpg&name=large",
      gallery_img_2: "https://pbs.twimg.com/media/FfeDi8JUYAAjoTF?format=jpg&name=large",
      gallery_img_3: "https://pbs.twimg.com/media/FdSJa6yUAAErdk0?format=jpg&name=large",
      gallery_img_4: "https://pbs.twimg.com/media/FdSJa6xVEAAelRv?format=jpg&name=large",
      gallery_img_5: "https://pbs.twimg.com/media/FcpomMVX0AoD7Bx?format=jpg&name=large",

      album: "Scaled And Icy",
      album_cover: "https://i.scdn.co/image/ab67616d00001e0220b467550945fd123e00f0a5",
      album_premiere: "2021",
      id: "11",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
      bio: "Twenty One Pilots shook the world with the release of their 2015 LP BLURRYFACE, an album that would go on to sell over 7 million copies worldwide and earn the band their first ever GRAMMY® Award as they shattered longstanding chart records, and captivated audiences worldwide on sold-out arena runs and at international festivals.  Now three years later, the duo of Tyler Joseph and Josh Dun have returned to write the next chapter of their story with TRENCH, the band’s highly anticipated new studio album.  TRENCH finds Twenty One Pilots fearlessly reimagining the possibilities of their music through the same candid expression and genuine identity that helped to cement their place as one of the largest bands in the world.",
      social:{
        instagram: "https://www.instagram.com/twentyonepilots/?theme=dark",
        twitter: "https://twitter.com/twentyonepilots",
        facebook: "https://www.facebook.com/twentyonepilots",
      },
      user_playlist_1: "",
  },
  {
      name: "Good Day",
      artist: "Twenty one pilots",
      colaboration: "",
      artist_status: "none",

      src: "TwentyOnePilots-GoodDay",
      img: "scaled-and-icy-b-iext104194001",
      style: "Chill",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f22bsf",
      artist_img: "https://i.scdn.co/image/ab6761610000e5eb196972172c37d934d9ca8093",
      gallery_img_1: "https://pbs.twimg.com/media/FfeDi8NVEAAcBE0?format=jpg&name=large",
      gallery_img_2: "https://pbs.twimg.com/media/FfeDi8JUYAAjoTF?format=jpg&name=large",
      gallery_img_3: "https://pbs.twimg.com/media/FdSJa6yUAAErdk0?format=jpg&name=large",
      gallery_img_4: "https://pbs.twimg.com/media/FdSJa6xVEAAelRv?format=jpg&name=large",
      gallery_img_5: "https://pbs.twimg.com/media/FcpomMVX0AoD7Bx?format=jpg&name=large",

      album: "Scaled And Icy",
      album_cover: "https://i.scdn.co/image/ab67616d00001e0220b467550945fd123e00f0a5",
      album_premiere: "2021",
      id: "12",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
      bio: "Twenty One Pilots shook the world with the release of their 2015 LP BLURRYFACE, an album that would go on to sell over 7 million copies worldwide and earn the band their first ever GRAMMY® Award as they shattered longstanding chart records, and captivated audiences worldwide on sold-out arena runs and at international festivals.  Now three years later, the duo of Tyler Joseph and Josh Dun have returned to write the next chapter of their story with TRENCH, the band’s highly anticipated new studio album.  TRENCH finds Twenty One Pilots fearlessly reimagining the possibilities of their music through the same candid expression and genuine identity that helped to cement their place as one of the largest bands in the world.",
      social:{
        instagram: "https://www.instagram.com/twentyonepilots/?theme=dark",
        twitter: "https://twitter.com/twentyonepilots",
        facebook: "https://www.facebook.com/twentyonepilots",
      },
      user_playlist_1: "",
  },
  {
      name: "Kłótnia",
      artist: "Evtis",
      colaboration: "",
      artist_status: "none",

      src: "Evtis-Kłótnia",
      img: "C-BooL-NeverGoAway",
      style: "Hip-Hop",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f106bsf",
      artist_img: "https://i.scdn.co/image/ab6761610000e5eb76a19046d32c54e79affd6a1",
      gallery_img_1: "",
      gallery_img_2: "",
      gallery_img_3: "",
      gallery_img_4: "",
      gallery_img_5: "",

      album: "Głosy",
      album_cover: "https://i.scdn.co/image/ab6761610000e5eb76a19046d32c54e79affd6a1",
      album_premiere: "2013",
      id: "13",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
      bio: "",
      social:{
        instagram: "",
        twitter: "",
        facebook: "https://www.facebook.com/Evtis",
      },
      user_playlist_1: "",
  },
  {
      name: "Idziemy Po Swoje",
      artist: "Szusty",
      colaboration: "DonGuralsko",
      artist_status: "none",

      src: "donGURALesko-IdziemyPoSwojeSzUstyBlend",
      img: "guralsko",
      style: "Workout",
      status: "nostatus",
      avatar: "41aeb62f0-c2321-f46bsf",
      artist_img: "https://i.scdn.co/image/ab6761610000e5eb4b346794a19f7adfcc244ee7",
      album: "Idziemy Po Swoje",
      album_cover: "https://i.scdn.co/image/ab67616d0000b273dd559af8356ea6b28a71a5fe",
      album_premiere: "2009",
      id: "14",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
      bio: "",
      social:{
        instagram: "https://www.instagram.com/szustyszesc/",
        twitter: "",
        facebook: "https://www.facebook.com/szustyblend",
      },
      user_playlist_1: "",
  },
  {
      name: "Legenda",
      artist: "Szusty",
      colaboration: "DonGuralsko",
      artist_status: "none",

      src: "donGURALesko-LegendaSzUstyBlend",
      img: "guralsko",
      style: "Workout",
      status: "nostatus",
      tag: "Popular",
      avatar: "41aeb62f0-c2321-f46bsf",
      artist_img: "https://i.scdn.co/image/ab6761610000e5eb4b346794a19f7adfcc244ee7",
      gallery_img_1: "",
      gallery_img_2: "",
      gallery_img_3: "",
      gallery_img_4: "",
      gallery_img_5: "",

      album: "Legenda",
      album_cover: "https://i.scdn.co/image/ab67616d00001e0259b80ddc896cb493dc68e697",
      album_premiere: "2010",
      id: "15",
      lyrics:{
        lyrics_verse_1: "",
        lyrics_verse_2: "",
        lyrics_verse_3: "",
        lyrics_verse_4: "",
        lyrics_verse_5: "",
        lyrics_verse_6: "",
        lyrics_verse_7: "",
        lyrics_verse_8: "",
        lyrics_verse_9: "",
        lyrics_verse_10: "",
        lyrics_verse_11: "",
        lyrics_verse_12: "",
        lyrics_verse_13: "",
        lyrics_verse_14: ""
      },
      bio: "",
      social:{
        instagram: "https://www.instagram.com/szustyszesc/",
        twitter: "",
        facebook: "https://www.facebook.com/szustyblend",
      },
      user_playlist_1: "",
  },
  {
    name: "Rockstar",
    artist: "Post Malone",
    colaboration: "",
    artist_status: "none",

    src: "PostMalone-Rockstar",
    img: "rockstar-w-iext111232885",
    style: "Pop",
    status: "nostatus",
    tag: "Popular",
    avatar: "41aeb62f0=c2321-f23bsf",
    artist_img: "https://i.scdn.co/image/ab6761610000e5ebb894ef9fa437b0389c5567cc",
    gallery_img_1: "https://pbs.twimg.com/media/FdIhyKfWYAUvVfo?format=jpg&name=large",
    gallery_img_2: "https://pbs.twimg.com/media/Fc5YuyNXEAEe_jb?format=jpg&name=large",
    gallery_img_3: "https://pbs.twimg.com/media/Fcabj0FWIAAKT6-?format=jpg&name=large",
    gallery_img_4: "https://pbs.twimg.com/media/FcVS25OXEAAjjk2?format=jpg&name=large",
    gallery_img_5: "https://pbs.twimg.com/media/EsshuO_W8AEl9xh?format=jpg&name=medium",

    album: "beerbongs & bentleys",
    album_cover: "https://i.scdn.co/image/ab67616d00001e02b1c4b76e23414c9f20242268",
    album_premiere: "2018",
    id: "16",
    lyrics:{
      lyrics_verse_1: "",
      lyrics_verse_2: "",
      lyrics_verse_3: "",
      lyrics_verse_4: "",
      lyrics_verse_5: "",
      lyrics_verse_6: "",
      lyrics_verse_7: "",
      lyrics_verse_8: "",
      lyrics_verse_9: "",
      lyrics_verse_10: "",
      lyrics_verse_11: "",
      lyrics_verse_12: "",
      lyrics_verse_13: "",
      lyrics_verse_14: ""
    },
    bio: "In 2016, he released the single Go Flex along with his official debut mixtape, August 26th. Months later, his first studio effort arrived. Stoney featured guests ranging from ",
    social:{
      instagram: "https://www.instagram.com/postmalone/",
      twitter: "https://twitter.com/postmalone",
      facebook: "https://www.facebook.com/postmalone",
    },
    user_playlist_1: "",
  },
  {
    name: "Bez Znieczulenia",
    artist: "Happysad",
    colaboration: "",
    artist_status: "none",

    src: "Happysad-Bezznieczulenia",
    img: "ab67616d00001e021f86dffe512418a230887e69",
    style: "Rock",
    status: "nostatus",
    avatar: "14235843737BeNz9sRRfK4jsYeLQ7t32Pg76m86w",
    artist_img: "https://i.scdn.co/image/ab6761610000e5ebd6e4988f56f08add19e0dd7b",
    gallery_img_1: "https://pbs.twimg.com/media/Ffi44c-WIAEp8dW?format=jpg&name=large",
    gallery_img_2: "https://pbs.twimg.com/media/Ffi44-jXwAMUldz?format=jpg&name=large",
    gallery_img_3: "",
    gallery_img_4: "",
    gallery_img_5: "",

    album: "Mów mi dobrze",
    album_cover: "https://i.scdn.co/image/ab67616d00001e021f86dffe512418a230887e69",
    album_premiere: "2009",
    id: "17",
    lyrics:{
      lyrics_verse_1: "",
      lyrics_verse_2: "",
      lyrics_verse_3: "",
      lyrics_verse_4: "",
      lyrics_verse_5: "",
      lyrics_verse_6: "",
      lyrics_verse_7: "",
      lyrics_verse_8: "",
      lyrics_verse_9: "",
      lyrics_verse_10: "",
      lyrics_verse_11: "",
      lyrics_verse_12: "",
      lyrics_verse_13: "",
      lyrics_verse_14: ""
    },
    bio: "Originating in Skarżysko-Kamienna in 2001, Happysad is a popular Polish rock band distinguished by friendly melodies and reggae-influenced rhythms. Their debut album, Wszystko Jedno, was issued by ",
    social:{
      instagram: "https://www.instagram.com/happysadpl",
      twitter: "",
      facebook: "https://www.facebook.com/happysadpl",
    },
    user_playlist_1: "",
  },
  {
    name: "Pętla",
    artist: "Happysad",
    colaboration: "",
    artist_status: "none",

    src: "Happysad-Pętla",
    img: "ab67616d00001e021f86dffe512418a230887e69",
    style: "Rock",
    status: "nostatus",
    tag: "Popular",
    avatar: "14235843737BeNz9sRRfK4jsYeLQ7t32Pg76m86w",
    artist_img: "https://i.scdn.co/image/ab6761610000e5ebd6e4988f56f08add19e0dd7b",
    gallery_img_1: "https://pbs.twimg.com/media/Ffi44c-WIAEp8dW?format=jpg&name=large",
    gallery_img_2: "https://pbs.twimg.com/media/Ffi44-jXwAMUldz?format=jpg&name=large",
    gallery_img_3: "",
    gallery_img_4: "",
    gallery_img_5: "",

    album: "Mów mi dobrze",
    album_cover: "https://i.scdn.co/image/ab67616d00001e021f86dffe512418a230887e69",
    album_premiere: "2009",
    id: "18",
    lyrics:{
      lyrics_verse_1: "",
      lyrics_verse_2: "",
      lyrics_verse_3: "",
      lyrics_verse_4: "",
      lyrics_verse_5: "",
      lyrics_verse_6: "",
      lyrics_verse_7: "",
      lyrics_verse_8: "",
      lyrics_verse_9: "",
      lyrics_verse_10: "",
      lyrics_verse_11: "",
      lyrics_verse_12: "",
      lyrics_verse_13: "",
      lyrics_verse_14: ""
    },
    bio: "Originating in Skarżysko-Kamienna in 2001, Happysad is a popular Polish rock band distinguished by friendly melodies and reggae-influenced rhythms. Their debut album, Wszystko Jedno, was issued by ",
    social:{
      instagram: "https://www.instagram.com/happysadpl",
      twitter: "",
      facebook: "https://www.facebook.com/happysadpl",
    },
    user_playlist_1: "",
  },
  {
    name: "Tired Bones",
    artist: "L.B.ONE",
    colaboration: "Leanz",
    artist_status: "none",

    src: "LBONE-TiredBones",
    img: "tired-bones-w-iext52557958",
    style: "Energic",
    status: "nostatus",
    avatar: "5cd42c454b86e992d288a65bd8a187b62151",
    artist_img: "https://i.scdn.co/image/ab6761610000e5eba6cbc503bf2aca8d539a7f92",
    gallery_img_1: "",
    gallery_img_2: "",
    gallery_img_3: "",
    gallery_img_4: "",
    gallery_img_5: "",

    album: "Lonely",
    album_cover: "https://i.scdn.co/image/ab67616d00001e021a2250d8502746a80d72da8d",
    album_premiere: "2018",
    id: "19",
    lyrics:{
      lyrics_verse_1: "",
      lyrics_verse_2: "",
      lyrics_verse_3: "",
      lyrics_verse_4: "",
      lyrics_verse_5: "",
      lyrics_verse_6: "",
      lyrics_verse_7: "",
      lyrics_verse_8: "",
      lyrics_verse_9: "",
      lyrics_verse_10: "",
      lyrics_verse_11: "",
      lyrics_verse_12: "",
      lyrics_verse_13: "",
      lyrics_verse_14: ""
    },
    bio: "Lianny BOUDJADI (L.B.ONE) is a French Electronic DJ-Producer. In 2017 he produce Across The Water feat Laenz and will be #1 radio charts in Russia and Ukraine. French solo artist most playlisted on eastern countries radio, a second single will follow Tired Bones and will be Number one in 15 eastern countries.",
    social:{
      instagram: "https://www.instagram.com/DJLBONE",
      twitter: "https://twitter.com/DJLBONE",
      facebook: "https://www.facebook.com/djlbone/",
    },
    user_playlist_1: "",
  },
  {
    name: "Złap Za Broń",
    artist: "Trzeci Wymiar",
    colaboration: "",
    artist_status: "none",

    src: "TrzeciWymiar-Złapzabroń",
    img: "6341ef2bd3abc2c21c6ee6466cb67d15.510x510x1",
    style: "Hip-Hop",
    status: "nostatus",
    avatar: "41aeb62f0-c2321-f24bsf",
    artist_img: "https://i.scdn.co/image/ab67616d0000b273cb498bab77f77940c83145fa",
    gallery_img_1: "",
    gallery_img_2: "",
    gallery_img_3: "",
    gallery_img_4: "",
    gallery_img_5: "",

    album: "Złodzieje Czasu",
    album_cover: "https://i.scdn.co/image/ab67616d00001e02d922659188234fee83318fe7",
    album_premiere: "2009",
    id: "20",
    lyrics:{
      lyrics_verse_1: "",
      lyrics_verse_2: "",
      lyrics_verse_3: "",
      lyrics_verse_4: "",
      lyrics_verse_5: "",
      lyrics_verse_6: "",
      lyrics_verse_7: "",
      lyrics_verse_8: "",
      lyrics_verse_9: "",
      lyrics_verse_10: "",
      lyrics_verse_11: "",
      lyrics_verse_12: "",
      lyrics_verse_13: "",
      lyrics_verse_14: ""
    },
    bio: "",
    social:{
      instagram: "",
      twitter: "",
      facebook: "",
    },
    user_playlist_1: "",
  },
  {
    name: "I'm Not Rich",
    artist: "The King's Son",
    colaboration: "Shaggy",
    artist_status: "none",

    src: "TheKingsSon-ImNotRich",
    img: "ab67616d0000b27369cdca7b90ca8060e3525196",
    style: "Chill",
    status: "nostatus",
    avatar: "41aeb62f0=c2321-f56bsf",
    artist_img: "https://i.scdn.co/image/2b9dc7ef187414be63e89488aef91f96c3e2170d",
    gallery_img_1: "",
    gallery_img_2: "",
    gallery_img_3: "",
    gallery_img_4: "",
    gallery_img_5: "",

    album: "The King",
    album_cover: "https://i.scdn.co/image/ab67616d00001e02ec999a8391a2dcb970f69cb0",
    album_premiere: "2015",
    id: "21",
    lyrics:{
      lyrics_verse_1: "",
      lyrics_verse_2: "",
      lyrics_verse_3: "",
      lyrics_verse_4: "",
      lyrics_verse_5: "",
      lyrics_verse_6: "",
      lyrics_verse_7: "",
      lyrics_verse_8: "",
      lyrics_verse_9: "",
      lyrics_verse_10: "",
      lyrics_verse_11: "",
      lyrics_verse_12: "",
      lyrics_verse_13: "",
      lyrics_verse_14: ""
    },
    bio: "",
    social:{
      instagram: "",
      twitter: "",
      facebook: "",
    },
    user_playlist_1: "",
  },
  {
    name: "Invincible",
    artist: "MGK",
    colaboration: "Ester Dean",
    artist_status: "none",

    src: "MGK-Invincible",
    img: "ab67616d0000b273a57d3a2736f815d3cf358e37",
    style: "Workout",
    status: "nostatus",
    avatar: "41aeb62f0=c2321-f57bsf",
    artist_img: "https://i.scdn.co/image/ab6761610000e5eb1fd54eb6e30d0bc8f633621e",
    gallery_img_1: "",
    gallery_img_2: "",
    gallery_img_3: "",
    gallery_img_4: "",
    gallery_img_5: "",

    album: "Start, GO",
    album_cover: "https://i.scdn.co/image/ab67616d0000b273cfac68443715de902bd7ea53",
    album_premiere: "2012",
    id: "22",
    lyrics:{
      lyrics_verse_1: "",
      lyrics_verse_2: "",
      lyrics_verse_3: "",
      lyrics_verse_4: "",
      lyrics_verse_5: "",
      lyrics_verse_6: "",
      lyrics_verse_7: "",
      lyrics_verse_8: "",
      lyrics_verse_9: "",
      lyrics_verse_10: "",
      lyrics_verse_11: "",
      lyrics_verse_12: "",
      lyrics_verse_13: "",
      lyrics_verse_14: ""
    },
    bio: "Delivering lyrics with the speed of a bullet train, Cleveland rapper Machine Gun Kelly experienced a meteoric rise in late 2011 when he transitioned from grinding out self-released mixtapes to working with major labels. From there, the rapper skyrocketed to superstar status, with each of his albums charting in the Top Ten. A beef with , a film career, and even some reality show appearances would follow as the high-powered lyrical rap style of albums like 2019's Hotel Diablo morphed into a driving emo-rock sound on collaborations with  and on the -produced 2020 album Tickets to My Downfall, which topped the Billboard 200. Kelly worked alongside  again in 2022 on album number six, Mainstream Sellout.",
    social:{
      instagram: "https://www.instagram.com/machinegunkelly/",
      twitter: "https://twitter.com/machinegunkelly",
      facebook: "https://www.facebook.com/machinegunkellymusic",
    },
    user_playlist_1: "",
  },
  {
    name: "In The Name Of Love",
    artist: "Bebe Rexha",
    colaboration: "",
    artist_status: "none",

    src: "BebeRexha-InTheNameOfLove",
    img: "ab67616d0000b2738c77bcf5f5a227d270d23370",
    style: "Energic",
    status: "nostatus",
    tag: "Popular",
    avatar: "41aeb62f0=c2321-f58bsf",
    artist_img: "https://i.scdn.co/image/ab6761610000e5ebabfac786f093c4da55c99d4e",
    gallery_img_1: "https://pbs.twimg.com/media/FbVolKlWIAERgoA?format=jpg&name=large",
    gallery_img_2: "https://pbs.twimg.com/media/FDM44l4VcAQ63Dk?format=jpg&name=large",
    gallery_img_3: "https://pbs.twimg.com/media/FdxDrgOVUAELbYS?format=jpg&name=large",
    gallery_img_4: "https://pbs.twimg.com/media/FZgNdvgVEAA7MLZ?format=jpg&name=large",
    gallery_img_5: "https://pbs.twimg.com/media/FGlY0TlVIAAhtb1?format=jpg&name=large",

    album: "In The Name Of Love",
    album_cover: "https://i.scdn.co/image/ab67616d0000b2738c77bcf5f5a227d270d23370",
    album_premiere: "2016",
    id: "23",
    lyrics:{
      lyrics_verse_1: "",
      lyrics_verse_2: "",
      lyrics_verse_3: "",
      lyrics_verse_4: "",
      lyrics_verse_5: "",
      lyrics_verse_6: "",
      lyrics_verse_7: "",
      lyrics_verse_8: "",
      lyrics_verse_9: "",
      lyrics_verse_10: "",
      lyrics_verse_11: "",
      lyrics_verse_12: "",
      lyrics_verse_13: "",
      lyrics_verse_14: ""
    },
    bio: "Rising as a songwriter for and , Brooklyn-born Bebe Rexha made her way from the studio to the stage, racking up hit singles with electronic artists (, , ), rappers (, , ), and even country duo , with whom she recorded the 2017 chart-topping country-pop crossover single Meant to Be. Although her work with other musicians has spanned genres, her own material centers on darker pop textures influenced by hip-hop and R&B, as heard on her debut, 2018's Expectations, and its 2021 follow-up Better Mistakes. Born Bleta Rexha in 1989, she began her musical journey at a young age. Performing in musicals from the age of four, she started to hone her skills in her early teens and was named Best Teen Songwriter at the National Academy of Recording Arts and Sciences annual Grammy Day event; she met a whole host of famous producers there. In 2010, Rexha was approached bys  to form the project , intended to reflects more experimental and electronic side. Rexha provided vocals for several EPs before she left the band in 2012 to embark on a solo career. She began uploading demos and acoustic covers to YouTube before signing with  in 2013.",
    social:{
      instagram: "https://www.instagram.com/beberexha",
      twitter: "https://twitter.com/beberexha",
      facebook: "https://www.facebook.com/beberexha",
    },
    user_playlist_1: "",
  },
  {
    name: "One Last Time",
    artist: "Ariana Grande",
    colaboration: "",
    artist_status: "none",
    
    src: "ArianaGrande-OneLastTime",
    img: "e63468347c14c9f580857daae877a005",
    style: "Energic",
    status: "nostatus",
    tag: "Popular",
    avatar: "ab67616d30590b273a25d3a2736f815d3cf358e37",
    artist_img: "https://i.scdn.co/image/d6a339d026361ec7f4daeac7126ce0f90662077a",
    gallery_img_1: "https://pbs.twimg.com/media/FfwoOn0WQAA7QeN?format=jpg&name=medium",
    gallery_img_2: "https://pbs.twimg.com/media/FepC6_3WQAQppla?format=jpg&name=medium",
    gallery_img_3: "https://pbs.twimg.com/media/FeGafYTWAAMNDSQ?format=jpg&name=large",
    gallery_img_4: "https://pbs.twimg.com/media/FbWeVmdWYAYn_qp?format=jpg&name=medium",
    gallery_img_5: "https://pbs.twimg.com/media/FYQoYGfWAAMZAdu?format=jpg&name=large",

    album: "Me Everything",
    album_cover: "https://i.scdn.co/image/ab67616d00001e02deec12a28d1e336c5052e9aa",
    album_premiere: "2014",
    id: "24",
    lyrics:{
      lyrics_verse_1: "",
      lyrics_verse_2: "",
      lyrics_verse_3: "",
      lyrics_verse_4: "",
      lyrics_verse_5: "",
      lyrics_verse_6: "",
      lyrics_verse_7: "",
      lyrics_verse_8: "",
      lyrics_verse_9: "",
      lyrics_verse_10: "",
      lyrics_verse_11: "",
      lyrics_verse_12: "",
      lyrics_verse_13: "",
      lyrics_verse_14: ""
    },
    bio: "Ariana Grande is perhaps the quintessential pop star of the last half of the 2010s, capturing the era's spirit and style. Emerging in 2013 with the hit single The Way, Grande initially appeared to be the heir to the throne of , due in part to her powerhouse vocals. With its  production, her debut Yours Truly underscored her debt to '90s R&B, but Grande quickly incorporated hip-hop and EDM into her music.",
    social:{
      instagram: "https://www.instagram.com/arianagrande/",
      twitter: "",
      facebook: "https://www.facebook.com/arianagrande",
    },
    user_playlist_1: "",
  },
  {
    name: "Friends",
    artist: "Anne Marie",
    colaboration: "Marshmallow",
    artist_status: "none",
    
    src: "https://drive.google.com/uc?export=view&id=1RxwKmEO9tK6m3WFxX5BMrZNHTftqi5zG",
    src: "Anne-Marie-Friends",
    img: "ab67616d00001e02569f6annemarie4493ca55cd96fdee412",
    style: "Energic",
    status: "nostatus",
    tag: "Popular",
    avatar: "3eff83c2098be9b7ebb770bca30ef66c21515",
    artist_img: "https://i.scdn.co/image/ab67616d00001e02a4dfacd3df2243b194f9e0a3",
    gallery_img_1: "https://pbs.twimg.com/media/FdA2h5NX0AkV7ZA?format=jpg&name=large",
    gallery_img_2: "https://pbs.twimg.com/media/FcEgLsyWYAQFNo7?format=jpg&name=large",
    gallery_img_3: "https://pbs.twimg.com/media/FbLEkrrUsAI6rQ7?format=jpg&name=large",
    gallery_img_4: "https://pbs.twimg.com/media/FatHfMAX0AE81An?format=jpg&name=large",
    gallery_img_5: "https://pbs.twimg.com/media/FWwUwCHXwAIMPqx?format=jpg&name=large",

    album: "F.R.I.E.N.D.S",
    album_cover: "https://i.scdn.co/image/ab67616d0000b273569f64493ca55cd96fdee412",
    album_premiere: "2018",
    id: "25",
    lyrics:{
      lyrics_verse_1: "",
      lyrics_verse_2: "",
      lyrics_verse_3: "",
      lyrics_verse_4: "",
      lyrics_verse_5: "",
      lyrics_verse_6: "",
      lyrics_verse_7: "",
      lyrics_verse_8: "",
      lyrics_verse_9: "",
      lyrics_verse_10: "",
      lyrics_verse_11: "",
      lyrics_verse_12: "",
      lyrics_verse_13: "",
      lyrics_verse_14: ""
    },
    bio: "Anne-Marie’s rise to stardom has been nothing short of meteoric. A former 3 x world karate champion and West End child star turned multi-platinum-selling artist, Anne-Marie has gone onto become one of the world’s most-loved and successful pop stars of our times",
    social:{
      instagram: "",
      twitter: "",
      facebook: "",
    },
    user_playlist_1: "",
  },
  {
    name: "Lovely",
    artist: "Billie Eilish",
    colaboration: "Khalid",
    artist_status: "none",
    
    src: "BillieEilish-Lovely",
    img: "ab67616d00001e028abille3f0a3ca7929dea23cd274cb",
    style: "Pop",
    status: "nostatus",
    tag: "Popular",
    avatar: "ab6761elish6d0000b27bille3a57d3a2736f815d3cf358e37",
    artist_img: "https://i.scdn.co/image/ab6761670000ecd474ab55d1d4b65d7f305d048b",
    gallery_img_1: "https://pbs.twimg.com/media/Ffkl-kKVEAAYQEb?format=jpg&name=large",
    gallery_img_2: "https://pbs.twimg.com/media/FfbcZOVXgAApFZT?format=jpg&name=900x900",
    gallery_img_3: "https://pbs.twimg.com/media/FfsVRTTXEAAHgJO?format=jpg&name=900x900",
    gallery_img_4: "https://pbs.twimg.com/media/FfyJjAiXgAIx90K?format=jpg&name=medium",
    gallery_img_5: "https://pbs.twimg.com/media/FfimZTCXkAAF95m?format=jpg&name=large",

    album: "lovely",
    album_cover: "https://i.scdn.co/image/ab67616d00001e028a3f0a3ca7929dea23cd274c",
    album_premiere: "2018",
    id: "26",
    lyrics:{
      lyrics_verse_1: "",
      lyrics_verse_2: "",
      lyrics_verse_3: "",
      lyrics_verse_4: "",
      lyrics_verse_5: "",
      lyrics_verse_6: "",
      lyrics_verse_7: "",
      lyrics_verse_8: "",
      lyrics_verse_9: "",
      lyrics_verse_10: "",
      lyrics_verse_11: "",
      lyrics_verse_12: "",
      lyrics_verse_13: "",
      lyrics_verse_14: ""
    },
    bio: "With the release of her highly anticipated sophomore album ‘Happier Than Ever,’ the 19-year-old Los Angeles native remains one of the biggest stars to emerge in the 21st century. Since the release of her debut single “ocean eyes” in 2015, Eilish continues to shatter the ceiling of music with her genre-defying sound. Fast forward from her humble breakout, her album WHEN WE ALL FALL ASLEEP, WHERE DO WE GO? debuted at No. 1 on the Billboard 200 in the U.S as well as 17 additional countries around the world upon release in 2019, and was the most streamed album of that year. WHEN WE ALL FALL ASLEEP, WHERE DO WE GO? was written, produced and recorded entirely by Billie Eilish and brother FINNEAS in their childhood home of Los Angeles. Billie Eilish went on to make history as the youngest artist to receive nominations and win in all the major categories at the 62nd GRAMMY® Awards, receiving an award for Best New Artist, Album of the Year, Record of the Year, Song of the Year, and Best Pop Vocal Album. Billie Eilish is also the youngest artist to write and record an official James Bond theme song, ‘No Time To Die.’ Most recently, Billie Eilish was nominated for four additional awards at the 63rd Annual GRAMMY Awards in 2021, and took home both Record of the Year for 'everything i wanted,' and Best Song Written For Visual Media for 'No Time To Die.’ Billie Eilish’s latest album ‘Happier Than Ever’ was written by Billie and her brother FINNEAS, who also produced the album.",
    social:{
      instagram: "https://www.instagram.com/billieeilish/",
      twitter: "https://twitter.com/billieeilish",
      facebook: "https://www.facebook.com/billieeilish",
    },
    user_playlist_1: "",
  },
  {
    name: "Symphony",
    artist: "Clean Bandit",
    colaboration: "Zara Larrson",
    artist_status: "none",
    
    src: "CleanBandit-Symphony",
    img: "ab67616d000clean01e0237fb0680110fbb107740de5d",
    style: "Energic",
    status: "nostatus",
    tag: "",
    avatar: "5cd42c454b86e9clean92d288a65bbanditd8a187b62151",
    artist_img: "https://i.scdn.co/image/ab6761670000ecd4b95f2591f7438f880bde75c4",
    gallery_img_1: "https://pbs.twimg.com/media/FgAa8-mWQAES3Yu?format=jpg&name=900x900",
    gallery_img_2: "https://pbs.twimg.com/media/FfhrpkBWIAAs1VH?format=jpg&name=large",
    gallery_img_3: "https://pbs.twimg.com/media/FffWVWTacAAEebR?format=jpg&name=large",
    gallery_img_4: "https://pbs.twimg.com/media/FV2ozDmWQAA-GqQ?format=jpg&name=large",
    gallery_img_5: "https://pbs.twimg.com/media/FNV2sN3XMAIslwU?format=jpg&name=large",

    album: "What Is Love?",
    album_cover: "https://i.scdn.co/image/ab67616d00001e0237fb0680110fbb107740de5d",
    album_premiere: "2018",
    id: "27",
    lyrics:{
      lyrics_verse_1: "",
      lyrics_verse_2: "",
      lyrics_verse_3: "",
      lyrics_verse_4: "",
      lyrics_verse_5: "",
      lyrics_verse_6: "",
      lyrics_verse_7: "",
      lyrics_verse_8: "",
      lyrics_verse_9: "",
      lyrics_verse_10: "",
      lyrics_verse_11: "",
      lyrics_verse_12: "",
      lyrics_verse_13: "",
      lyrics_verse_14: ""
    },
    bio: "British dance group Clean Bandit found crossover success by weaving classical music with dance-pop for a beat-driven yet refined sound -- often delivered with high-profile guest vocalists. After scoring their first hit with the multi-platinum international sensation Rather Be, featuring  (from 2014's New Eyes), they issued a string of U.K. chart-toppers that proved successful around the world, including Rockabye with  and Anne-Marie, Symphony with , and Solo with , all of which were included on 2018's What Is Love? They again reached the U.K. Top Ten with 2020's Tick Tock featuring before releasing 2021's Higher with",
    social:{
      instagram: "https://www.instagram.com/cleanbandit/",
      twitter: "https://twitter.com/cleanbandit",
      facebook: "https://www.facebook.com/cleanbandit",
    },
    user_playlist_1: "",
  },
  {
    name: "Radioactive",
    artist: "Imagine Dragons",
    colaboration: "",
    artist_status: "none",
    
    src: "ImagineDragonsRadioactive",
    img: "effimagineR-dragons-5966452-1407607955-4124",
    style: "Pop",
    status: "nostatus",
    tag: "",
    avatar: "MC43MzkxNjEwimagineMCAxNjI1Mzg5Njc2sef",
    artist_img: "https://i.scdn.co/image/ab6761670000ecd4b33c0ac2fda166767b9dbc1a",
    gallery_img_1: "https://i.scdn.co/image/ab6761670000ecd4efe8ca4b5dc7ac9030ce4d59",
    gallery_img_2: "https://i.scdn.co/image/ab6761670000ecd44e31fd349dd7c17a93cc4598",
    gallery_img_3: "https://pbs.twimg.com/media/Fc4GtsiWYAIwTcF?format=jpg&name=large",
    gallery_img_4: "https://pbs.twimg.com/media/Fc4GtshWIAIl2nU?format=jpg&name=large",
    gallery_img_5: "https://pbs.twimg.com/media/Fc4GtsoXwAEudCM?format=jpg&name=large",

    album: "Night Visions",
    album_cover: "https://i.scdn.co/image/ab67616d00001e02407bd04707c463bbb3410737",
    album_premiere: "2012",
    id: "28",
    lyrics:{
      lyrics_verse_1: "",
      lyrics_verse_2: "",
      lyrics_verse_3: "",
      lyrics_verse_4: "",
      lyrics_verse_5: "",
      lyrics_verse_6: "",
      lyrics_verse_7: "",
      lyrics_verse_8: "",
      lyrics_verse_9: "",
      lyrics_verse_10: "",
      lyrics_verse_11: "",
      lyrics_verse_12: "",
      lyrics_verse_13: "",
      lyrics_verse_14: ""
    },
    bio: "Formed in 2009, Imagine Dragons first revealed their emotionally charged and inventive sensibilities with a series of independently released EPs that earned them grassroots following. Signed to KIDinaKORNER/Interscope by hitmaking producer Alex Da Kid, the band greatly expanded their fanbase with the release of their multi-platinum breakthrough single “It’s Time” (featured on the 2012 EP Continued Silence). With their past hits also including “Radioactive” (a diamond-selling smash that won Best Rock Performance at the 2014 Grammy Awards), Imagine Dragons went on to see Smoke + Mirrors debut at #1 on the Billboard Top 200 album chart upon its release in early 2015.",
    social:{
      instagram: "https://www.instagram.com/imaginedragons/",
      twitter: "https://twitter.com/Imaginedragons",
      facebook: "https://www.facebook.com/ImagineDragons",
    },
    user_playlist_1: "",
  },
  {
    name: "Beliver",
    artist: "Imagine Dragons",
    colaboration: "",
    artist_status: "none",
    
    src: "ImagineDragonsBeliever",
    img: "ab67616d0imagine000b273a57d3adra2736f815d3gonscf358e37",
    style: "Pop",
    status: "nostatus",
    tag: "",
    avatar: "MC43MzkxNjEwimagineMCAxNjI1Mzg5Njc2sef",
    artist_img: "https://i.scdn.co/image/ab6761670000ecd4b33c0ac2fda166767b9dbc1a",
    gallery_img_1: "https://i.scdn.co/image/ab6761670000ecd4efe8ca4b5dc7ac9030ce4d59",
    gallery_img_2: "https://i.scdn.co/image/ab6761670000ecd44e31fd349dd7c17a93cc4598",
    gallery_img_3: "https://pbs.twimg.com/media/Fc4GtsiWYAIwTcF?format=jpg&name=large",
    gallery_img_4: "https://pbs.twimg.com/media/Fc4GtshWIAIl2nU?format=jpg&name=large",
    gallery_img_5: "https://pbs.twimg.com/media/Fc4GtsoXwAEudCM?format=jpg&name=large",

    album: "Evolve",
    album_cover: "https://i.scdn.co/image/ab67616d00001e025675e83f707f1d7271e5cf8a",
    album_premiere: "2017",
    id: "29",
    lyrics:{
      lyrics_verse_1: "",
      lyrics_verse_2: "",
      lyrics_verse_3: "",
      lyrics_verse_4: "",
      lyrics_verse_5: "",
      lyrics_verse_6: "",
      lyrics_verse_7: "",
      lyrics_verse_8: "",
      lyrics_verse_9: "",
      lyrics_verse_10: "",
      lyrics_verse_11: "",
      lyrics_verse_12: "",
      lyrics_verse_13: "",
      lyrics_verse_14: ""
    },
    bio: "Formed in 2009, Imagine Dragons first revealed their emotionally charged and inventive sensibilities with a series of independently released EPs that earned them grassroots following. Signed to KIDinaKORNER/Interscope by hitmaking producer Alex Da Kid, the band greatly expanded their fanbase with the release of their multi-platinum breakthrough single “It’s Time” (featured on the 2012 EP Continued Silence). With their past hits also including “Radioactive” (a diamond-selling smash that won Best Rock Performance at the 2014 Grammy Awards), Imagine Dragons went on to see Smoke + Mirrors debut at #1 on the Billboard Top 200 album chart upon its release in early 2015.",
    social:{
      instagram: "https://www.instagram.com/imaginedragons/",
      twitter: "https://twitter.com/Imaginedragons",
      facebook: "https://www.facebook.com/ImagineDragons",
    },
    user_playlist_1: "",
  },
  {
    name: "Bleeding Out",
    artist: "Imagine Dragons",
    colaboration: "",
    artist_status: "none",
    
    src: "ImagineDragonsBleedingOut",
    img: "6ef9bc2988b796965f42098c459a83a6",
    style: "Pop",
    status: "nostatus",
    tag: "",
    avatar: "MC43MzkxNjEwimagineMCAxNjI1Mzg5Njc2sef",
    artist_img: "https://i.scdn.co/image/ab6761670000ecd4b33c0ac2fda166767b9dbc1a",
    gallery_img_1: "https://i.scdn.co/image/ab6761670000ecd4efe8ca4b5dc7ac9030ce4d59",
    gallery_img_2: "https://i.scdn.co/image/ab6761670000ecd44e31fd349dd7c17a93cc4598",
    gallery_img_3: "https://pbs.twimg.com/media/Fc4GtsiWYAIwTcF?format=jpg&name=large",
    gallery_img_4: "https://pbs.twimg.com/media/Fc4GtshWIAIl2nU?format=jpg&name=large",
    gallery_img_5: "https://pbs.twimg.com/media/Fc4GtsoXwAEudCM?format=jpg&name=large",

    album: "Evolve",
    album_cover: "https://i.scdn.co/image/ab67616d00001e025675e83f707f1d7271e5cf8a",
    album_premiere: "2017",
    id: "30",
    lyrics:{
      lyrics_verse_1: "",
      lyrics_verse_2: "",
      lyrics_verse_3: "",
      lyrics_verse_4: "",
      lyrics_verse_5: "",
      lyrics_verse_6: "",
      lyrics_verse_7: "",
      lyrics_verse_8: "",
      lyrics_verse_9: "",
      lyrics_verse_10: "",
      lyrics_verse_11: "",
      lyrics_verse_12: "",
      lyrics_verse_13: "",
      lyrics_verse_14: ""
    },
    bio: "Formed in 2009, Imagine Dragons first revealed their emotionally charged and inventive sensibilities with a series of independently released EPs that earned them grassroots following. Signed to KIDinaKORNER/Interscope by hitmaking producer Alex Da Kid, the band greatly expanded their fanbase with the release of their multi-platinum breakthrough single “It’s Time” (featured on the 2012 EP Continued Silence). With their past hits also including “Radioactive” (a diamond-selling smash that won Best Rock Performance at the 2014 Grammy Awards), Imagine Dragons went on to see Smoke + Mirrors debut at #1 on the Billboard Top 200 album chart upon its release in early 2015.",
    social:{
      instagram: "https://www.instagram.com/imaginedragons/",
      twitter: "https://twitter.com/Imaginedragons",
      facebook: "https://www.facebook.com/ImagineDragons",
    },
    user_playlist_1: "",
  },
  {
    name: "Bad Liar",
    artist: "Imagine Dragons",
    colaboration: "",
    artist_status: "none",
    
    src: "ImagineDragonsBadLiar",
    img: "6ef9bc2988b7969bad65f42098liarc459a83a6",
    style: "Pop",
    status: "nostatus",
    tag: "",
    avatar: "MC43MzkxNjEwimagineMCAxNjI1Mzg5Njc2sef",
    artist_img: "https://i.scdn.co/image/ab6761670000ecd4b33c0ac2fda166767b9dbc1a",
    gallery_img_1: "https://i.scdn.co/image/ab6761670000ecd4efe8ca4b5dc7ac9030ce4d59",
    gallery_img_2: "https://i.scdn.co/image/ab6761670000ecd44e31fd349dd7c17a93cc4598",
    gallery_img_3: "https://pbs.twimg.com/media/Fc4GtsiWYAIwTcF?format=jpg&name=large",
    gallery_img_4: "https://pbs.twimg.com/media/Fc4GtshWIAIl2nU?format=jpg&name=large",
    gallery_img_5: "https://pbs.twimg.com/media/Fc4GtsoXwAEudCM?format=jpg&name=large",

    album: "Origins",
    album_cover: "https://i.scdn.co/image/ab67616d00001e02da6f73a25f4c79d0e6b4a8bd",
    album_premiere: "2018",
    id: "31",
    lyrics:{
      lyrics_verse_1: "",
      lyrics_verse_2: "",
      lyrics_verse_3: "",
      lyrics_verse_4: "",
      lyrics_verse_5: "",
      lyrics_verse_6: "",
      lyrics_verse_7: "",
      lyrics_verse_8: "",
      lyrics_verse_9: "",
      lyrics_verse_10: "",
      lyrics_verse_11: "",
      lyrics_verse_12: "",
      lyrics_verse_13: "",
      lyrics_verse_14: ""
    },
    bio: "Formed in 2009, Imagine Dragons first revealed their emotionally charged and inventive sensibilities with a series of independently released EPs that earned them grassroots following. Signed to KIDinaKORNER/Interscope by hitmaking producer Alex Da Kid, the band greatly expanded their fanbase with the release of their multi-platinum breakthrough single “It’s Time” (featured on the 2012 EP Continued Silence). With their past hits also including “Radioactive” (a diamond-selling smash that won Best Rock Performance at the 2014 Grammy Awards), Imagine Dragons went on to see Smoke + Mirrors debut at #1 on the Billboard Top 200 album chart upon its release in early 2015.",
    social:{
      instagram: "https://www.instagram.com/imaginedragons/",
      twitter: "https://twitter.com/Imaginedragons",
      facebook: "https://www.facebook.com/ImagineDragons",
    },
    user_playlist_1: "",
  },
  {
    name: "Born To Be Yours",
    artist: "Kygo",
    colaboration: "Imagine Dragons",
    artist_status: "none",
    
    src: "KygoImagineDragonsBornToBeYours",
    img: "ab67616d0000b27337084df74688999caf0cbb9f",
    style: "Chillout",
    status: "nostatus",
    tag: "",
    avatar: "5cd42c454b1255eaekygo992d288a65bd8a187b62151",
    artist_img: "https://i.scdn.co/image/ab6761670000ecd4344976180e7bc5d4e4283c0a",
    gallery_img_1: "https://i.scdn.co/image/f6db8882992e201807a86891436e97988e60e73a",
    gallery_img_2: "https://pbs.twimg.com/media/EsV1VhAXYAc3Gyb?format=jpg&name=large",
    gallery_img_3: "https://pbs.twimg.com/media/Eou5qZ0XIAYROuq?format=jpg&name=large",
    gallery_img_4: "https://pbs.twimg.com/media/EiImFeoXkAAZEz0?format=jpg&name=large",
    gallery_img_5: "https://pbs.twimg.com/media/EdI7r9yXgAAA0gz?format=jpg&name=large",

    album: "Born To Be Yours",
    album_cover: "https://i.scdn.co/image/ab67616d00001e02d355c4cf741193b97849af1a",
    album_premiere: "2018",
    id: "32",
    lyrics:{
      lyrics_verse_1: "",
      lyrics_verse_2: "",
      lyrics_verse_3: "",
      lyrics_verse_4: "",
      lyrics_verse_5: "",
      lyrics_verse_6: "",
      lyrics_verse_7: "",
      lyrics_verse_8: "",
      lyrics_verse_9: "",
      lyrics_verse_10: "",
      lyrics_verse_11: "",
      lyrics_verse_12: "",
      lyrics_verse_13: "",
      lyrics_verse_14: ""
    },
    bio: "Whether behind the piano in his studio or headlining a sold-out festival, Kygo quietly reaffirms his status as a prodigious talent, forward-thinking producer, dynamic DJ, and influential global superstar. The Norwegian musician born Kyrre Gørvell-Dahll first introduced himself in 2013 and quietly became one of the most ubiquitous hitmakers in the world while emerging as Spotify’s “Breakout Artist of 2015.” “Firestone” ft. Conrad Sewell and “Stole the Show” ft. Parson James help cement Kygo as “the fastest artist to reach 1 billion streams on Spotify.” In the wake of his chart-topping 2016 full- length debut Cloud Nine, he delivered memorable performances on The Late Late Show with James Corden, Good Morning America, The Tonight Show Starring Jimmy Fallon, and The Ellen DeGeneres Show. Plus, he notably performed “Carry Me” during the Closing Ceremony of the Rio Olympics.",
    social:{
      instagram: "https://www.instagram.com/imaginedragons/",
      twitter: "https://twitter.com/Imaginedragons",
      facebook: "https://www.facebook.com/ImagineDragons",
    },
    user_playlist_1: "",
  },
]